.travis.yml, mne_neuron/basket.py, mne_neuron/cell.py, mne_neuron/dipole.py, mne_neuron/feed.py, mne_neuron/fileio.py, mne_neuron/network.py, mne_neuron/paramrw.py, mne_neuron/params_default.py, mne_neuron/pyramidal.py, setup.cfg
=> TST check pep8 on travis

.travis.yml, doc/index.rst, mne_neuron/pyramidal.py
=> Fix parconn bug

examples/plot_simulate_evoked.py, mne_neuron/paramrw.py
=> ENH: easy filtering of params

doc/api.rst, examples/plot_simulate_alpha.py, examples/plot_simulate_evoked.py, mne_neuron/__init__.py, mne_neuron/dipole.py, mne_neuron/network.py, mne_neuron/tests/test_params.py
=> ENH: plot inputs as histogram

doc/Dockerfile, doc/conf.py
=> ENH: add binder links

examples/plot_simulate_evoked.py, mne_neuron/dipole.py, mne_neuron/params_default.py, mne_neuron/tests/test_dipole.py, param/default.json
Part of issue #41. @jasmainak Please see comments for the other fix needed. Once added to this pull request, the output should checkout out with HNN.
=> Fix scaling

CONTRIBUTING.rst, examples/README.txt
closes https://github.com/jasmainak/mne-neuron/issues/53 and https://github.com/jasmainak/mne-neuron/issues/54
cc @blakecaldwell
=> ENH: fixes to contributing guide

CONTRIBUTING.rst, doc/api.rst, doc/whats_new.rst, examples/plot_simulate_alpha.py, examples/plot_simulate_evoked.py, examples/plot_simulate_somato.py, hnn_core/__init__.py, hnn_core/params.py, hnn_core/tests/test_cell.py, hnn_core/tests/test_compare_hnn.py, hnn_core/tests/test_dipole.py, hnn_core/tests/test_network.py, hnn_core/tests/test_params.py
Params can load a .param file with flag 'is_json=False'
=> ENH: support legacy HNN param files

hnn_core/params.py, hnn_core/tests/test_params.py
This will work to read existing HNN parameter files without doing anything fancy to handle comments or invalid lines.
=> Support HNN legacy params

.circleci/config.yml, README.rst, doc/api.rst, doc/parallel.rst, hnn_core/basket.py, hnn_core/neuron.py
closes #116 
just some cleaning up
cc @blakecaldwell @rythorpe
=> [MRG] Reorganize install

hnn_core/basket.py, hnn_core/cell.py, hnn_core/neuron.py, hnn_core/pyramidal.py
I was really misled by the name "`connect_to_target`". The actual connection happens when you call `_PC.gid_connect` inside `_Cell.parconnect_from_src`
=> MAINT: better naming of function to set up netcon

.circleci/artifact_path, doc/conf.py, doc/roadmap.rst
cc @stephanie-r-jones 
see rendering: https://132-168215891-gh.circle-artifacts.com/0/html/roadmap.html
To build locally:
```sh
$ git clone git@github.com:jonescompneurolab/hnn-core.git
$ cd hnn-core
$ git remote add jasmainak git@github.com:jasmainak/hnn-core.git
$ git fetch jasmainak roadmap:roadmap
$ git checkout roadmap
```
then edit `roadmap.rst`. To see the rendered html, do:
```sh
$ cd doc/
$ make html-noplot
```
and open the `_build/html/roadmap.html` file in a web browser. Once happy with the edits, push them:
```py
$ git add roadmap.rst
$ git commit -m "Updates to the roadmap"
$ git push jasmainak roadmap
```
Hopefully all this works. Let me know if you get any errors
=> ENH: add roadmap

doc/api.rst, hnn_core/dipole.py, hnn_core/network.py, hnn_core/tests/test_dipole.py, hnn_core/tests/test_network.py, hnn_core/viz.py
as discussed in the roadmap.
TODO:
=> [MRG] MAINT: refactor viz functions

examples/plot_simulate_alpha.py, examples/plot_simulate_gamma.py, hnn_core/dipole.py, hnn_core/feed.py, hnn_core/tests/test_dipole.py, hnn_core/viz.py
Better variable names are always a good idea to relax on a Friday evening ... :)
=> [MRG] MAINT: better variable naming

hnn_core/mpi_child.py, hnn_core/parallel_backends.py, hnn_core/tests/test_compare_hnn.py
This uses the well-known `select()` mechanism to wait for input from `mpi_child.py` in MPIBackend. A signal is sent by the child (string "sim_complete") to let MPIBackend know that it has received all output that should be printed to the screen (stdout and stderr) and to expect simulation data as a pickled object.
Resolves #192
=> [MRG] use selectors to get output and data from mpi_child.py

hnn_core/feed.py, hnn_core/tests/test_feed.py
It's an easy issue but I decided to tackle it since we have a bit of a time crunch
closes #180 
cc @blakecaldwell @rythorpe
=> [MRG] validate poisson input times

doc/_templates/autosummary/class.rst, doc/conf.py, hnn_core/basket.py, hnn_core/cell.py, hnn_core/pyramidal.py, hnn_core/tests/test_cell.py
This is setting the stage for #165 . Might take more than one PR.
Very much work in progress right now
=> MRG: start cleaning up geometry

hnn_core/cell.py, hnn_core/mod/dipole_pp.mod, hnn_core/network_builder.py
modeled after https://github.com/Neurosim-lab/netpyne/pull/470/files by @blakecaldwell 
I just started the PR to declare my intention to work on this. 
<s>Probably #175 can also be tackled in the same issue ... we'll see</s> (I have run out of patience ...)
=> MRG: Remove global dipole variable

examples/plot_firing_pattern.py
@ntolley just some tiny tweaks. Is this good by you?
=> DOC: tweaks to firing rate example

README.rst, hnn_core/cell.py
=> [MRG] MAINT: replace h.setpointer with _ref_blah

doc/api.rst, doc/whats_new.rst, examples/plot_firing_pattern.py, examples/plot_simulate_evoked.py, examples/plot_simulate_somato.py, hnn_core/__init__.py, hnn_core/cell.py, hnn_core/dipole.py, hnn_core/network.py, hnn_core/network_builder.py, hnn_core/parallel_backends.py, hnn_core/params_default.py, hnn_core/pyramidal.py, hnn_core/tests/test_dipole.py, hnn_core/tests/test_network.py, hnn_core/tests/test_parallel_backends.py, hnn_core/viz.py
closes #187. Starting this PR early to keep track of modifications discussed in #193 
**To-do**
=> [MRG] Add functionality to record current from all cells

doc/whats_new.rst, hnn_core/viz.py
closes #227. Individual gids are now separately plotted in the spike raster. Example:
=> [MRG] ENH: Add single gid plotting to plot_spikes_raster()

setup.py
Stumbled across this outdated description, good timing considering the upcoming release!
@jasmainak look good with you?
=> [MRG] DOC: Update setup.py description

MANIFEST.in, Makefile, setup.cfg
=> [MRG] TST add check-manifest to CI

README.rst
cc @stephanie-r-jones let me know if something else needs to be clarified
closes #257
=> DOC: clarify installation

examples/plot_simulate_gamma.py, hnn_core/externals/mne.py, hnn_core/viz.py
This removes any dependency on MNE.
=> MRG: Add TFR functions to externals

.circleci/config.yml, doc/_templates/navbar.html, doc/conf.py
=> [MRG] DOC: support multiple versions

.circleci/config.yml, doc/Makefile
=> DOC: makefile

hnn_core/drives.py, hnn_core/network.py
@cjayb a tiny cosmetic improvement so that the init of `Network` remains compact and easy to read. Let me know what you think
=> [MRG] MAINT: move drives creation to drives.py

LICENSE
@cjayb what do you think of adding the Brown University license in the interim that we wait for @stephanie-r-jones to hear back ?
It's at least more permissive than having no license at all ... but less permissive than BSD-3
=> [MRG] ENH: add license

.circleci/config.yml, .travis.yml, doc/Makefile, doc/_templates/navbar.html, doc/conf.py, doc/whats_new.rst, examples/plot_simulate_somato.py, hnn_core/__init__.py
The goal of this PR is to clarify the somato example by
=> [MRG] DOC: reference background material in somato example

doc/roadmap.rst
Creating a PR from @stephanie-r-jones documentation updates.
=> [MRG] Doc updates

hnn_core/drives.py, hnn_core/tests/test_drives.py
=> [MRG] DOC: better error message

hnn_core/dipole.py, hnn_core/drives.py, hnn_core/mpi_child.py, hnn_core/network.py, hnn_core/network_builder.py, hnn_core/parallel_backends.py, hnn_core/tests/test_dipole.py, hnn_core/tests/test_network.py
Addresses https://github.com/jonescompneurolab/hnn-core/issues/307.
=> [MRG, BUG] Make params private

CONTRIBUTING.rst
Addresses https://github.com/jonescompneurolab/hnn-core/issues/311.
=> [MRG, DOC] Fix contributing install instructions

hnn_core/__init__.py, hnn_core/cell_response.py, hnn_core/network.py
=> [MRG] MAINT: read_spikes -> cell_response.py

README.rst, doc/whats_new.rst, hnn_core/__init__.py, hnn_core/cell.py, hnn_core/cells_default.py, hnn_core/params_default.py, hnn_core/viz.py
closes #326 
I tried not to touch too much so others can continue with their PRs
=> [MRG] compute yscale from cell points

doc/whats_new.rst, hnn_core/drives.py, hnn_core/network.py, hnn_core/params.py, hnn_core/tests/test_drives.py, hnn_core/tests/test_network.py
=> [MRG] MAINT: remove 'uniform' option in add_bursty_drive

CODE_OF_CONDUCT.md
Needed for CZI grant (copied from HNN repo)
cc @stephanie-r-jones
=> [MAINT][MRG] Add Code of Conduct

examples/plot_simulate_evoked.py, hnn_core/cell.py, hnn_core/cells_default.py, hnn_core/network.py, hnn_core/params_default.py, hnn_core/tests/test_viz.py, hnn_core/viz.py
Thanks to #321 we can now get rid of some cruft from our code.
=> [MRG] VIZ move plot_morphology to cell object

.circleci/config.yml, doc/conf.py
=> Update roadmap in maint version

hnn_core/network.py
=> [MRG] fix layers 5 and 2 swapped depth dimension

hnn_core/network.py, hnn_core/tests/test_network.py
The goal of this PR is to facilitate future adding new cell types more easily and update pos_dict and gid_ranges consistently
=> [MRG] update pos_dict and gid_ranges more consistently

hnn_core/cell.py, hnn_core/cell_response.py, hnn_core/network.py, hnn_core/network_builder.py, hnn_core/tests/test_network.py
I realized that it may not be too difficult to have a function to add a new cell population. While you may disagree if `hnn-core` should really be doing this, I think it will improve the code anyway. Started with tests though so it improves the internal API ... not sure it's ready for public API prime time yet.
=> [MRG] MAINT: improve _add_cell_type even further

hnn_core/tests/test_network.py
@cjayb @ntolley 
I think this should have been fixed before merge though ...
=> [MRG] Rebase issue

doc/whats_new.rst, examples/howto/plot_connectivity.py, examples/howto/plot_firing_pattern.py, examples/howto/plot_record_extracellular_potentials.py, examples/howto/plot_simulate_mpi_backend.py, examples/workflows/plot_simulate_alpha.py, examples/workflows/plot_simulate_beta.py, examples/workflows/plot_simulate_evoked.py, examples/workflows/plot_simulate_gamma.py, examples/workflows/plot_simulate_somato.py, hnn_core/dipole.py, hnn_core/parallel_backends.py, hnn_core/tests/conftest.py, hnn_core/tests/test_dipole.py, hnn_core/tests/test_extracellular.py, hnn_core/tests/test_parallel_backends.py, hnn_core/tests/test_viz.py
=> [MRG] do not smooth or scale by default

.github/workflows/linkcheck.yml, .github/workflows/unit_tests.yml, README.rst, doc/Makefile, doc/conf.py, doc/roadmap.rst, examples/workflows/plot_simulate_somato.py
=> [MRG] MAINT: add linkcheck

hnn_core/extracellular.py, hnn_core/network_builder.py, hnn_core/tests/test_extracellular.py
closes #358 
this was really bugging me as I started reviewing #370 so I'm going to take a stab at it
=> [MRG] only numpy arrays in extracellular

doc/whats_new.rst, examples/howto/plot_connectivity.py, examples/howto/plot_firing_pattern.py, examples/howto/plot_record_extracellular_potentials.py, examples/howto/plot_simulate_mpi_backend.py, examples/workflows/plot_simulate_alpha.py, examples/workflows/plot_simulate_beta.py, examples/workflows/plot_simulate_evoked.py, examples/workflows/plot_simulate_gamma.py, examples/workflows/plot_simulate_somato.py, hnn_core/cell_response.py, hnn_core/dipole.py, hnn_core/drives.py, hnn_core/mpi_child.py, hnn_core/network.py, hnn_core/network_builder.py, hnn_core/network_models.py, hnn_core/parallel_backends.py, hnn_core/tests/conftest.py, hnn_core/tests/test_cell_response.py, hnn_core/tests/test_dipole.py, hnn_core/tests/test_drives.py, hnn_core/tests/test_extracellular.py, hnn_core/tests/test_mpi_child.py, hnn_core/tests/test_network.py, hnn_core/tests/test_parallel_backends.py, hnn_core/tests/test_viz.py
supercedes #315 
second attempt, we'll go with simpler route this time ...
=> [MRG] Simulate dipole tstop

hnn_core/dipole.py, hnn_core/drives.py, hnn_core/mpi_child.py, hnn_core/network.py, hnn_core/network_builder.py, hnn_core/parallel_backends.py, hnn_core/tests/conftest.py, hnn_core/tests/test_mpi_child.py, hnn_core/tests/test_network.py
Follow up #397 so I don't forget. Not critical for 0.2 release
Also need to remove:
https://github.com/jonescompneurolab/hnn-core/blob/af26624dac0fd495575e627420a60b7d5b403b67/hnn_core/drives.py#L144-L145
as suggested in [this comment](https://github.com/jonescompneurolab/hnn-core/pull/397#discussion_r678024474)
=> [MRG] FIX: tstop cleanup

hnn_core/cells_default.py, hnn_core/network_models.py, hnn_core/tests/test_network.py
Closes #411. Luckily this fix was fairly straightforward. Na channels now exhibit linearly decreasing gbar, and K channels exhibit exponentially decreasing gbar with respect to distance from soma.
=> [MRG] Add distance dependent Na and K channels to calcium_model

doc/conf.py, doc/glossary.rst, examples/workflows/plot_simulate_alpha.py, examples/workflows/plot_simulate_beta.py
closes #390 
I started a glossary, please feel free to correct and/or add new items.
I just want to get the ball rolling and we can make this better in future PRs
cc @Moham-Amin @rythorpe
=> [MRG] Start glossary

doc/whats_new.rst, examples/howto/optimize_evoked.py, hnn_core/dipole.py, hnn_core/tests/test_dipole.py
=> [MRG] FIX: allow reading experimental dipole

hnn_core/parallel_backends.py
=> [MRG] MAINT: psutil should be optional dependency

hnn_core/extracellular.py
Reverts #401 as suggested in #409.
Closes #408
=> [MRG] Revert ptr_update_callback fixes segfaults

examples/workflows/plot_simulate_beta.py, examples/workflows/plot_simulate_gamma.py, hnn_core/cell.py, hnn_core/cells_default.py, hnn_core/network_builder.py, hnn_core/network_models.py, hnn_core/tests/test_cell.py, hnn_core/tests/test_cells_default.py, hnn_core/tests/test_network.py, hnn_core/viz.py
=> [MRG] MAINT: p_secs -> sections

examples/howto/optimize_evoked.py, examples/howto/plot_connectivity.py, examples/howto/plot_firing_pattern.py, examples/howto/plot_simulate_mpi_backend.py, examples/workflows/plot_simulate_alpha.py, examples/workflows/plot_simulate_evoked.py, examples/workflows/plot_simulate_gamma.py, examples/workflows/plot_simulate_somato.py, hnn_core/network.py, hnn_core/network_models.py, hnn_core/tests/test_network.py
closes #402 
Just removing some boilerplate code. What do people think? Not editing tests right now because `N_Pyr_x` and `N_Pyr_y` is not exposed through API
=> [MRG] DOC: hide read_params

doc/_templates/search.html
closes #437 
@rythorpe @ntolley if you can merge this before we meet for the release tomorrow that would be great
=> [MRG] BUG: Fix for Sphinx 3.4+ search

examples/howto/optimize_evoked.py, examples/workflows/plot_simulate_evoked.py
updates evoked example demonstrating how to add a synchronous drive
closes #424
=> [MRG] minor example documentation updates

.circleci/config.yml, examples/workflows/plot_simulate_alpha.py
=> [MRG] ENH: make alpha example clearer

examples/workflows/plot_simulate_evoked.py
Adding a warning message to Tutorial 01. Simulate Event Related Potentials (ERPs): 
- Always look at dipoles in conjunction with raster plots and spike histogram to avoid misinterpretation.                
- Run multiple trials of your simulation to get an average of different drives seeds before drawing conclusions.
=> [MRG] DOC: Establish best practice guide for analyzing simulation output

doc/whats_new.rst, examples/workflows/plot_simulate_evoked.py, hnn_core/tests/test_viz.py, hnn_core/viz.py
=> [WIP] Iterate over layers when plotting dipole

doc/whats_new.rst, examples/howto/plot_connectivity.py, hnn_core/network.py
closes #356 
* Changed conn_seed default to None from 3
* Updated docstring
* Untested (probably will break)
=> [MRG] Randomly generated default conn_seed

setup.py
=> [MRG] Include ipynb during installation

hnn_core/gui/gui.py, hnn_core/tests/test_gui.py
=> [MRG] Remove connection probability inputs

.github/workflows/linkcheck.yml, .gitignore, doc/conf.py, doc/gui/index.rst, doc/gui/tutorial_erp.ipynb, hnn_core/gui/gui.py, hnn_core/tests/test_gui.py
* Added first ERP tutorial (unfinished). 
* Exposed few methods used to manipulate the GUI
=> [MRG] hnn-core GUI ERP partial tutorial

hnn_core/gui/gui.py, hnn_core/tests/test_gui.py
Users now can run multiple simulations and compare them. Also simplified some layout init functions
=> [MRG] Add multi-simulation support

examples/howto/plot_record_extracellular_potentials.py, examples/workflows/plot_simulate_evoked.py, hnn_core/extracellular.py, hnn_core/viz.py
I need for my tutorial, so I'll take the beginner's issue :) 
closes #503
=> [MRG] Sane defaults for LFP

.mailmap
Second attempt at this ... let's see if this works
=> MAINT: show blake in contributors

doc/parallel.rst
=> [MRG] DOC: set DYLD_FALLBACK_LIBRARY in parallel backend installation instructions for mac

Makefile, README.rst, doc/contributing.rst
More verbose description of the pull request process for new contributors.
=> [MRG] DOC: Update contributing guide and windows install

README.rst, doc/gui/tutorial_erp.ipynb, hnn_core/gui/gui.py, hnn_core/tests/test_gui.py
=> [MRG] Separate loading drives and loading connectivity

.github/workflows/unit_tests.yml, README.rst, doc/conf.py, doc/gui/index.rst
=> [MRG][DOC] Tweaks to the docs

.github/workflows/unit_tests.yml, doc/api.rst, doc/whats_new.rst, examples/howto/plot_record_extracellular_potentials.py, hnn_core/extracellular.py, hnn_core/tests/test_extracellular.py, hnn_core/viz.py
The goal of this PR is to begin integrating current source density estimation/plotting capabilities into the API. A first example implementation is included.
=> [MRG]: current source density estimation

doc/gui/tutorial_erp.ipynb, hnn_core/cell_response.py, hnn_core/dipole.py, hnn_core/gui/_viz_manager.py, hnn_core/gui/gui.py, hnn_core/tests/test_gui.py, hnn_core/viz.py
Now one can safely delete a spectrogram plot without changing the figure layout.
Notice this involves some changes to the original spectrogram viz function and we may have to make it non-default (or not?)
=> [MRG] Adaptive colorbar for spectrogram plots & dynamic x-axis alignment

README.rst
=> [MRG] Specify python >3.0 in readme

.circleci/config.yml
Fix the conda installation problem. Close #581
=> Fix conda error

.github/workflows/unit_tests.yml, .github/workflows/windows_unit_tests.yml, MANIFEST.in, README.rst, hnn_core/network_builder.py, pyproject.toml, setup.py
I haven't tested it properly but I think this would make the installation process more robust
=> [MRG] MAINT: robustify install for different platforms

.circleci/build_cache, .circleci/config.yml
=> [MRG] Fix circleci timeout problem

doc/conf.py, hnn_core/gui/_viz_manager.py
In the past, it was common for the y-axis to disappear after editing or creating a figure. A protection mechanism is added now to prevent such bugs.
=> [MRG] Fix axis label missing bug

doc/Makefile
=> [MRG] Disable notebook execution when necessary

.circleci/config.yml, .github/workflows/linkcheck.yml, README.rst, doc/conf.py, doc/contributing.rst, setup.py
With @wagdy88 we realized that conda environments always don't come with python, so it might be better to put Python in the requirements.
=> [MRG] Python requires

hnn_core/gui/gui.py, hnn_core/tests/test_gui.py
=> [MRG] Fix wrong slider type

doc/gui/tutorial_erp.ipynb, hnn_core/network_models.py
=> [MRG] Add references to network model documentation

doc/whats_new.rst, hnn_core/optimization.py, hnn_core/tests/test_optimization.py
Now optimize_evoked returns the unweighted RMSE values for each optimization iteration.
=> [MRG] Added return rmse to  optimize_evoked

README.rst, hnn_core/dipole.py, hnn_core/gui/_viz_manager.py, hnn_core/gui/gui.py, hnn_core/tests/test_gui.py
Closes #607 
Now, we can upload external data by clicking on the "load data" button located under the "simulation" tab. Please note that the location of the button is temporary, and we can decide together whether it should remain there later.
=> [MRG] Add loading data button

.github/DISCUSSION_TEMPLATE/installation.yml
I see myself asking the same questions to people when they report their installation issues. We can iterate and refine this as we get more complaints ...
=> [MRG] DOC: add template for reporting installation issues

hnn_core/gui/_viz_manager.py
=> [MRG] Add RMSE

doc/whats_new.rst, hnn_core/cell_response.py, hnn_core/tests/test_viz.py, hnn_core/viz.py
=> [MRG] ENH: Add option to customize spike histogram colors

doc/whats_new.rst, hnn_core/dipole.py, hnn_core/tests/test_dipole.py, setup.py
- Added write method for dipole
- Added read method for dipole
- Added required tests
=> [MRG] Added read/write methods and tests for dipole

hnn_core/cell_response.py, hnn_core/tests/test_cell_response.py
- Reverted read/write hdf5 functions and their associated tests
- Added warnings for read/write using txt format and associated tests
- Added to_dict method
=> [ENH] Reverted hdf5 functions and added to_dict method

README.rst
=> [MRG] DOC: add 'About' section to README.rst

doc/network_file_desc.rst
=> Update network_file_desc.rst typos

hnn_core/gui/gui.py
added logic to reset the file uploaded widget value to zero after a file has been uploaded
=> [MRG] Reset File Upload Widget to Zero

.gitignore
Closes #738 
- Updated `.gitignore` to ignore Virtual Environment directories
=> [MRG] Added Virtual Environment Directories to `.gitignore`

doc/whats_new.rst, hnn_core/gui/gui.py, hnn_core/tests/test_gui.py
1. Added gui support for Synchronous Inputs in drivers simulations
2. Checkbox initial value loaded from values in default.json
Solves #716
=> [ENH]: GUI - Synchronous Inputs

hnn_core/__init__.py, hnn_core/gui/gui.py
Noticed that the private function was added to the package's init file. Changed the gui's import of the function to be directly from the dipole module and removed it from the package's init file.
=> [MRG] Refactor: Changed gui import of _read_dipole_text function 

.github/workflows/issue-metrics.yml
Implementing issue metric tracking through github workflows: https://github.com/github/issue-metrics/blob/main/docs/search-query.md
Once merged this workflow will create a report in the form of an issue that details statistics on issues raised and response times.
=> WIP: Add issue metrics action

.github/workflows/issue-metrics.yml
Fixes #790 to use a cron schedule
=> [MRG] Set monthly schedule for issue metrics

README.rst
Updated Neuron download link as indicated in #801 
solves #801
=> [DOC] Update neuron download link

examples/howto/plot_batch_simulate.py, hnn_core/__init__.py, hnn_core/batch_simulate.py, hnn_core/tests/test_batch_simulate.py
A follow-up PR to extend and refine the functionality of `BatchSimulate`.
=> [MRG] ENH: Advanced Features and Optimization in `BatchSimulate`

hnn_core/gui/_viz_manager.py
Fixing bug on the available plot type list in the viz tab
solves #832 
solves #831
=> [MRG] Bug: Incomplete Plot types list in visualization tab

hnn_core/gui/gui.py, hnn_core/tests/test_gui.py
Removed the sorting of drive widgets alphabetically.
Discussed in #850
=> [MRG] GUI: fix drive sorting

hnn_core/gui/gui.py, hnn_core/tests/test_gui.py
Updated the GUI load drive widget to be able to load tonic biases from a network config file.
=> [MRG] feat: GUI tonic loading

hnn_core/gui/gui.py, hnn_core/hnn_io.py, hnn_core/tests/test_gui.py
Button to download network configurations to json.
=> [MRG] GUI export configurations

README.rst
Added link to new GUI image for readme
=> [MRG] Update README.rst GUI image

hnn_core/__init__.py
Using this PR for pushing a 2nd prelease to PyPI before SfN presentations
@dylansdaniels @jasmainak can one of you merge this so I can try testing the pip install?
=> [MRG] Prelease `0.4rc1`

hnn_core/gui/_viz_manager.py
Changed default smoothing for simulation dipoles to 0.
=> [MRG] change default smoothing for dipoles to 0

hnn_core/__init__.py
Updating prelease for bug fixes to run a class tutorial
=> [MRG] Increment prerelease to RC3

hnn_core/network.py
Fix for issue #974. No formatting this time ;)
=> Remove the word "leading" from docstring

doc/whats_new.md, examples/howto/plot_connectivity.py, hnn_core/tests/test_viz.py, hnn_core/viz.py
i have removed the unnecessary dependecies and added an example in plot_connectivity.py via taking some pre defined external drives and also added one for convenience .i have also updated the unit section ,the test case is pending
=> [MRG] Add drive strength plotting

hnn_core/network.py
=> [MRG] added docstring to _add_cell_type_bias arguments

hnn_core/gui/_viz_manager.py
Change template Layer-Specific Dipole (3x1) figure to consider all three subplots when determining the ylims of the axes
=> [MRG] GUI layer-specific dipole axes

hnn_core/gui/_viz_manager.py, hnn_core/gui/gui.py, hnn_core/tests/test_gui.py
Adds scaling to the default visualization parameters in the GUI
=> [MRG] add scaling to default visualization parameters

hnn_core/network.py, hnn_core/utils.py
Follow up from #1044 ... hopefully the correct branches now. Tests seem to pass locally
=> Simplify rename_cell_type

doc/install.md
linkcheck, oh linkcheck
how thou frustrates me
=> doc: fix textbook usage links after url update

.github/workflows/codespell.yml, .github/workflows/linkcheck.yml, .github/workflows/publish-packages-on-tag.yml, .github/workflows/publish-to-test-pypi.yml, .github/workflows/unix_unit_tests.yml, .github/workflows/windows_unit_tests.yml, doc/conf.py, hnn_core/__init__.py
This PR is for testing an attempt to change our build process to use Github Acitons -> Pypi, a la https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ .
All non-building workflows have been commented out.
=> [MRG]: pkg: test initial Github building
