.travis.yml
doc/whats_new.rst
mne_neuron/basket.py
mne_neuron/pyramidal.py
mne_neuron/tests/test_compare_hnn.py

closes #41 
cc @blakecaldwell 
This should be equivalent to your fixes here: https://github.com/jasmainak/mne-neuron/commit/8f43e18a8ba6a3107acb2ef5195c65aea9cc7039
can you give it a try?

FIX extra autapse connection

---

README.rst
doc/api.rst
doc/whats_new.rst
examples/plot_simulate_evoked.py
mne_neuron/__init__.py
mne_neuron/dipole.py
mne_neuron/feed.py
mne_neuron/network.py
mne_neuron/parallel.py
mne_neuron/params.py
mne_neuron/tests/test_compare_hnn.py
mne_neuron/tests/test_network.py

@blakecaldwell thanks to your PR I think we might be able to get embarrassingly parallel working pretty easily! This is a bit WIP but I'm quite positive it will work. More soon ...

MRG: make joblib work

---

doc/conf.py
doc/whats_new.rst
hnn_core/feed.py
hnn_core/params.py
hnn_core/tests/test_compare_hnn.py
hnn_core/tests/test_network.py

There is some odd behavior in how rhythmic inputs are handled. The default param set avoids loading and running `extinput` inputs (i.e., rhythmic inputs) by assigning the start time, `t0`, to a time after `tstop`. If, however, someone loads the default param file and then modifies it so that `t0` lies within the simulation timeline, the dipole changes. See the attached example script (a modified version of "plot_simulate_evoked.py" and its corresponding terminal outputs. Currently, the attached script creates this image along with "original_terminal_out.txt": 
The commit in this PR creates this image along with "fixed_terminal_out.txt":
Note that my proposed fix might mess with the current rng seeds.
[extinput_demo.zip](https://github.com/jonescompneurolab/hnn-core/files/4484546/extinput_d …

Fix extinput (rhythmic) input param feed

---

doc/whats_new.rst
hnn_core/feed.py
hnn_core/tests/test_feed.py
hnn_core/tests/test_network.py

This PR fixes the part of #98 (specifically 94fc21a6 in `feed.py`) that botches the alpha-example.
No test written yet, input appreciated! There's a refactor brewing (see also discussion in #98), so perhaps tests should be deferred? To speed up tests, would it make sense to create a 'minimal network'? Not sure that makes sense, but almost 3 min spent on just the full alpha-example isn't sustainable. 
Fixes #101

[MRG] fix logic checking extinput synweights zero

---

hnn_core/basket.py
hnn_core/cell.py
hnn_core/feed.py
hnn_core/network.py
hnn_core/params.py
hnn_core/pyramidal.py
hnn_core/tests/test_compare_hnn.py
hnn_core/tests/test_feed.py
hnn_core/tests/test_network.py
hnn_core/tests/test_params.py

This PR is an attempt to clarify the code in terms of "external inputs" a.k.a. "external feeds". A lot of the diff is cosmetic, _e.g._, variable name changes. New tests and validations are also included.
One key point is renaming `extinput` to `common`. Our instinct was to go for `rhythmic`, as that's the only thing these are [currently used for](https://jonescompneurolab.github.io/hnn-tutorials/alpha_and_beta/alpha_and_beta). However, the input mechanism is completely generic and could in principle support non-rhythmic inputs as well (_e.g._, Poisson bursts?).
The parameter handling of "common" and "unique" external feeds is still a little opaque in the code, but this should clarify. A future refactor/PR could remove the `ExtFeed` class (and parameter dicts) in favour of functions with …

[MRG] cleanup variable names and logic related to "common" inputs

---

doc/api.rst
doc/whats_new.rst
examples/plot_simulate_evoked.py
examples/plot_simulate_somato.py
hnn_core/__init__.py
hnn_core/dipole.py
hnn_core/network.py
hnn_core/tests/test_compare_hnn.py
hnn_core/tests/test_dipole.py
hnn_core/tests/test_network.py

Two changes have been made: 1) `dipole.write()` has been fixed to save files according to the user-specified name, and 2) `network.write_spikes()` has been added so that spiking data for selected trials can be saved to a single .txt file. See the attached example (a modified version of the plot_simulate_evoked.py example) and its corresponding output .txt and .png files that demonstrates reconstruction of the simulated spike event plot using the spike .txt files.
[demo.zip](https://github.com/jonescompneurolab/hnn-core/files/4391152/demo.zip)

Fix dipole and network (spiking) class write methods

---

examples/plot_simulate_evoked.py
hnn_core/network.py

This PR achieves few improvements:
1. Create all the coordinates in one function so that you modify `pos_dict` in only place not multiple methods
2. Reuse variables such as `xrange`
3. Rename `xrange` to `xxrange` since `xrange` is a Python builtin
4. Take `_create_coords` out of the class so it is explicit what goes in for this computation and what comes out (Zen of Python says: "Explicit is better than implicit.")
5. Reduce the number of attributes in `Network` class. No more `zdiff` attribute and `gridpyr` attribute
cc @rythorpe @blakecaldwell

[MRG] Reorganize creating coordinates.

---

doc/api.rst
doc/whats_new.rst
hnn_core/__init__.py
hnn_core/dipole.py
hnn_core/tests/test_dipole.py

Split from #83 for a fast merge

[MRG] ENH: add average_dipoles function to Dipole

---

doc/whats_new.rst
hnn_core/basket.py
hnn_core/cell.py
hnn_core/pyramidal.py
hnn_core/tests/test_cell.py

Just a tiny adjustment to the code inspired by #129 . 
We need to develop more high level interfaces but this is a start. The challenge in this PR would be to keep it under control and not touch everything :)
will add a similar method to `L2Pyr` and then basket cells. Then it's good to go

[MRG] MAINT: refactor distal/proximal stuff

---

examples/plot_firing_pattern.py
hnn_core/cell.py
hnn_core/mpi_child.py
hnn_core/network_builder.py
hnn_core/parallel_backends.py
hnn_core/tests/test_cell.py
hnn_core/tests/test_network.py
hnn_core/viz.py

@blakecaldwell I was having trouble doing import of "from neuron import h" in the same folder as `hnn_core` because there was this file with the same name. I think this name is clearer and avoids this problem. Let me know what you think.

[MRG] MAINT: move neuron -> neuron_network

---

doc/api.rst
doc/whats_new.rst
examples/plot_simulate_evoked.py
examples/plot_simulate_somato.py
hnn_core/network.py
hnn_core/tests/test_network.py
hnn_core/viz.py

closes #135. Moves `network.plot_input()` to `network.spikes.plot_input()` (tests and examples updated to reflect this). 
Adds new argument `spike_types` to function call. Examples calls included below:
`spikes.plot_input(spike_types=['evprox1', 'evdist1','evprox2']`
`spikes.plot_input(spike_types={'Early': ['evprox1', 'evdist1'], 'Late': ['evprox2']})`
`spikes.plot_input(spike_types={'Evoked': ['ev']})`

[MRG] ENH: plot_input() accepts flexible spike_types argument

---

doc/whats_new.rst
hnn_core/mpi_child.py
hnn_core/network_builder.py
hnn_core/parallel_backends.py
hnn_core/tests/test_compare_hnn.py

fixes #136 
Running the code [here](https://gist.github.com/rythorpe/e7bac070bff41f108996b98c8b58ac14) creates this plot with `MPI_Backend`:
and this plot for `JoblibBackend`:
Note that while individual trials are not exactly the same between the two versions (most likely due to an inconsistency in the trajectories of random states), both show 10 distinct trials that emerged from distinct random states. If anyone can readily spot where the discrepancy is occurring it be much appreciated. Otherwise we might want to address that in another PR since the tests are still passing.
This PR also addresses some of the inconsistent messaging that gets output during a simulation in the terminal.

[MRG] fix inconsistent random state assignment between parallel trials

---

hnn_core/params_default.py
hnn_core/tests/test_params.py

HNN GUI needs this parameter and the only want to have it load into a `Params` object is to have a default value. When spectrograms are implemented in hnn-core such that they can be used by the GUI in dialogs, then this parameter can probably be removed.

Add 'spec_cmap' paramter for use by HNN GUI

---

doc/parallel.rst
hnn_core/mpi_child.py
hnn_core/parallel_backends.py
hnn_core/tests/test_compare_hnn.py

Previously, we had to wait for the MPI simulation to complete before any
output would be printed on the console. This commit uses the non-blocking select
call to print stderr and stdout while the simulation is in progress.
With MPIBackend we pass the simulation results back via stderr, which means that
MPI error messages during the simulation. We use base64 padding characters to
separate the data from the MPI messages. A trick with base64 encoding is to use
b'===' to always ensure that the padding offset is correct, but also having
something to indicate the boundary before the error message.
Fixes #112

[MRG] ENH: print MPI simulation messages to console

---

hnn_core/feed.py
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/params.py
hnn_core/viz.py

This PR has very limited scope: all it really does is
The latter is mostly done in `Network`, with minor consequences to `NetworkBuilder`.
Note that nothing has happened to the creation of the 'feed' spike sequences, which will be addressed in a subsequent PR.
Partial PR on the way to #104

[MRG] Separate external "feed" creation in Network from real cells

---

doc/whats_new.rst
examples/plot_simulate_evoked.py
hnn_core/network.py
hnn_core/parallel_backends.py
hnn_core/tests/test_network.py

closes #154 
not sure if this is the right way to do it, just opening a "work in progress thing" and we can discuss the details. How is the spike rate typically calculated?
TODO

[MRG] ENH: Function to get spike rates

---

hnn_core/basket.py
hnn_core/cell.py
hnn_core/pyramidal.py

MRG: Improve cells

---

hnn_core/mpi_child.py
hnn_core/parallel_backends.py
hnn_core/tests/conftest.py
hnn_core/tests/test_mpi_child.py
hnn_core/tests/test_parallel_backends.py
pytest.ini

This should address the issues with #190, finally (I've tested on a rebased branch with code from #190). The key fix was simple: 2e425c53ad60fe223ede18050a52d047c2202447. When the system is slow (e.g. Travis) is might accumulate more than 4k in the stderr buffer and only the first 4k would get read.
During the search for this bug, I made many improvements that should make life easier for everyone going forward. The changes to the MPI child communication scheme have a bunch of unit tests. The largest change for discussion is the testing scheme code for parallel backends... @jasmainak @rythorpe @ntolley 
It drove me mad trying to fix Travis issues when the time to complete tests and print errors is ~10 minutes. While we are still validating the MPIBackend and adding new simuatlion outputs, …

[MRG]: BUG: fix MPI child communication, add several improvements w/ unit testing

---

doc/whats_new.rst
examples/plot_firing_pattern.py
examples/plot_simulate_evoked.py
hnn_core/basket.py
hnn_core/cell.py
hnn_core/dipole.py
hnn_core/mpi_child.py
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/parallel_backends.py
hnn_core/pyramidal.py
hnn_core/tests/test_cell.py
hnn_core/tests/test_feed.py
hnn_core/tests/test_network.py
hnn_core/tests/test_parallel_backends.py

Based on the work done in #177, continue creating new API for adding (and activating/simulating) external drives of the network (currently 'feeds'). Some ideas are discussed in a separate Doc (contact @cjayb for access). This is going to be a test-breaking PR due to very idiosyncratic handling of random seeds used in HNN-GUI feed assignment.
Edit 6 Nov:
Discussed GID-handling with @jasmainak and figured much could be won by disentangling it from NetworkBuilder. As it stands, `Network` creates the `gid_dict` on initialisation, so all that's really left for `Builder` to do is assign them to the different nodes (ranks).
Aims
* turned out not to be needed
For future PR
- demonstrate API ideas to allow incrementally adding drives
- create new tests of `Network` event times
- create new …

[MRG] Refactor creation of network 'feeds' (to allow new mechanism for adding network drives)

---

doc/whats_new.rst
hnn_core/__init__.py
hnn_core/feed.py
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/tests/test_feed.py

Giving this another shot. To complement efforts by @cjayb

MRG: improve feeds

---

doc/whats_new.rst
examples/plot_simulate_evoked.py
hnn_core/dipole.py
hnn_core/network_builder.py
hnn_core/parallel_backends.py
hnn_core/pyramidal.py
hnn_core/tests/conftest.py
hnn_core/tests/test_dipole.py
hnn_core/tests/test_parallel_backends.py

postprocessing

---

examples/plot_simulate_alpha.py

This clarifies which parameters are being changed in the default parameter set in order to create the alpha example. Specifically, I propose that we explicitly remove all parameters that pertain to proximal or distal evoked feeds. Note that the simulation produced on my branch (shown below) matches the [alpha simulation](https://jonescompneurolab.github.io/hnn-core/auto_examples/plot_simulate_alpha.html#sphx-glr-auto-examples-plot-simulate-alpha-py) produced on master.

[MRG] clarify alpha example by removing evoked inputs

---

hnn_core/network.py

This fixes a silent discrepancy that emerged from time-to-time where a change in the codebase causes the random state for inter-trial variance to iterate recursively across trials. For example, the current master branch will take a gid of 1 and iterate the next trial's prng_seedcore value using the previous trial's value as reference. The set of prng_seedcore values across trials is thus {1+0=1, 1+1=2, 2+2=4, 4+3=7, ...} when we expect it to be {1+0=1, 1+1=2, 1+2=3, ...}.
The plot below shows that with https://github.com/jonescompneurolab/hnn-core/commit/959f94681c41edbc2dab5795d4c31d9771557f67, the output of 4 trials run with `default.json`/`default.param` is consistent between hnn and hnn-core. The top plot shows trials generated with hnn-core, the bottom plot shows trials generated …

MRG: fix reference to initial prng seedcore params

---

doc/whats_new.rst
hnn_core/tests/test_dipole.py
hnn_core/viz.py

closes #240. Quick fix for raster plot when no spikes occur during simulation. Now a blank plot is returned.
Decided against raising a warning as a lack of spikes is pretty self explanatory. 
Also snuck that doc nitpick in @jasmainak ;)

[MRG] Fix raster with no spikes

---

Makefile

On starting with a fresh `hnn-core` clone, I found that the make-process was botched. Anyone else?

[MRG] fix build path in Makefile (and recursive rm)

---

examples/plot_simulate_gamma.py
hnn_core/network.py
hnn_core/tests/test_feed.py

closes #223 
I was messing around with the gamma examples and realized that HNN-GUI uses a morlet wavelet for TFR. This is an attempt to make them more similar and add a colorbar. 
While I was at it, I also updated the tonic input example and made a couple of fixes there.

[MRG] DOC: use morlet instead of multitaper

---

doc/whats_new.rst
hnn_core/network.py
hnn_core/tests/test_network.py

This should change the read_spikes function to address issue_178. I'm not sure how to drop the change I made to the testing file, so please get rid of that somehow.
closes #178

Changes read_spikes

---

README.rst

Added passage on where to find docs and examples (this is not clear to people new to `pip`-installed packages etc.).  Also added some suggestions on more interactive ways to work through examples.
Closes #258

[MRG] README add section on Doc and Examples (#258)

---

hnn_core/viz.py

Addresses @stephanie-r-jones comment in #258.
Raster plots now stack cells in the correct order by layer:

[MRG] MAINT: Fix cell ordering in raster plots

---

doc/api.rst
examples/plot_simulate_alpha.py

Adding more detailed descriptions to alpha wave example. Additionally updating simulation to match alpha and beta tutorial provided in HNN-GUI (https://jonescompneurolab.github.io/hnn-tutorials/alpha_and_beta/alpha_and_beta)

[MRG] DOC: Update alpha example

---

examples/plot_simulate_somato.py
hnn_core/network.py
hnn_core/param/N20.json
hnn_core/viz.py

[MRG] DOC: update somato example

---

examples/plot_simulate_evoked.py

Looks like part of the example was accidentally deleted in #254 . This is just bringing it back

[MRG] DOC: incomplete example

---

README.rst
doc/conf.py
doc/whats_new.rst
hnn_core/__init__.py
hnn_core/viz.py
pyproject.toml
setup.py

Release vp1

---

.travis.yml

Attempt to fix codecov reports ... let's see 
TODO
- <s>check if it's a mac issue: https://community.codecov.io/t/code-is-tested-but-not-covered-by-codecov/831/3 </s>
- check history to see which commit dropped the codecov?
- try what's specified here: https://stackoverflow.com/questions/58527463/using-pytest-coverage-and-codecov-io-with-python

[MRG] MAINT: fix codecov

---

.coveragerc
hnn_core/tests/test_viz.py
hnn_core/viz.py

Follow-up to #281 : excluding `externals` (and `tests`) from coverage report illustrates where we should focus attention to (e.g. `viz.py` is trailing behind the rest...).

[MRG] add .coveragerc to exclude externals

---

hnn_core/parallel_backends.py

Transferring simulation data from mpi_child to MPIBackend can take a
long time when there is spectral data and/or somatic voltages to send
back for multiple trials. Make this faster by increasing the data read
from stdout/stderr file descriptors for each event dectected on the
selector.
This reduced the time to complete a HNN GUI simulation with 3 trials,
spec, and somatic voltage data from 6.5 minutes to 1 minute.

MRG: ENH: speed up moving results from mpi_child

---

hnn_core/dipole.py
hnn_core/network.py
hnn_core/tests/test_network.py

`net.cell_response` must be reset (lists emptied) in `simulate_dipole` to prevent cell response attributes being appended. The use case is pathological (see #290 and the gist therein), but may come up during optimisation?
Closes #290

[MRG] reset net.cell_response in simulate_dipole

---

doc/parallel.rst
hnn_core/externals/mne.py
hnn_core/mpi_child.py
hnn_core/parallel_backends.py
hnn_core/tests/test_dipole.py
hnn_core/tests/test_mpi_child.py
hnn_core/tests/test_parallel_backends.py

Select is not compatible with windows (see #215), so we can
follow the same scheme MNE uses with a thread that reads from
stdin/stdout/stderr and appeands line-by-line to a queue. The
main process can then read from the queue. Implements non-
blocking read and is a bit faster than the old _read_all_bytes
function, even with #287.
Also add cleanup processes on KeyboardInterrupt that kill any
running nrniv processes.
Closes #285 and #215

MRG: use Queue in MPIBackend for non-blocking read

---

hnn_core/tests/test_parallel_backends.py

A typo here kept MPI backend from running. Default Joblib backend was being compared to itself.

MRG: fix test_compare_hnn_core

---

hnn_core/parallel_backends.py
hnn_core/tests/test_mpi_child.py
hnn_core/tests/test_parallel_backends.py

This method will be called asynchronously by HNN GUI. So we need to use a lock to protect the variable declaring whether the simulation should terminate.
Killing nrniv procs are done in two places, and only in hnn-core. First, when the context manager exits, as this is basically state is only valid within the manager. Second, when a terminate() call is made specifically. The user may desire to run multiple simulations within a single MPIBackend context manager.

MRG: add terminate method to MPIBackend

---

hnn_core/parallel_backends.py
hnn_core/tests/test_parallel_backends.py

The os.sched_getaffinity(0) call on Travis (Linux) would return 2, thus limiting n_procs to 2 for MPIBackend and not allowing the oversubscribe CI test to run with 3 processors.
Note some clusters set scheduler affinity to limit jobs on shared resources. This change means that the user will be responsible for setting n_procs appropriately and not exceeding resource reservations.

MRG: fix MPI oversubscribe test on travis

---

.gitignore

For developers' git convenience it seems like a good idea to have a .gitignore so as not to accidentally push the `__pycache__`s  etc. Is there a reason not to do this?
It seems like it's not so simple because the `build_mod` makes the dynamic libraries in a directory named after the architecture (e.g. `hnn_core/mod/x86_64/`) so that might have to be refactored or put somewhere else so that it can be properly ignored. I didn't do that part yet because that's a rather larger change and I wanted to make sure this was the way to go first.
Also this .gitignore is copied from `mne-bids` so there might be another one that would be better to copy too.

[MRG, ENH] Add .gitignore

---

examples/plot_connectivity.py
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/tests/test_network.py

Closes #298. The current change reduces the size of `net.connectivity` (default network) from 55 MB to 10 MB. I think this could be further reduced by changing how src-target pairs are enumerated. Specifically:
```py
{'gid_pairs': (src_gid1, [target_gid1, target_gid2, ...]), (src_gid2, [target_gid1, target_gid2, ...]), ...}
```
Also I think this will be a good opportunity to discuss better high level API's. For sparse connectivity, I think the simplest implementation would be adding a probability argument to `net.add_connection()` that defaults to 1.0, and randomly removes connections passed via `gid_pairs`. 
The previous API allowed for passing a single `src_gid`, and a list of `target_gids`. I can certainly restore that ability with helper function, but my feeling is it won't be that …

[MRG] ENH: Improve connectivity data structure

---

hnn_core/network_builder.py

NEURON 8.0.0 makes a change in something to do with "dynamic units". This leads to slight (floating point precision-level) differences in the output of our Dipole time courses. 
The issue was first noted in #322.
References:
https://github.com/neuronsimulator/nrn/pull/746
https://github.com/neuronsimulator/nrn/blob/c8cb9878b5b46c9a116315037b963d77828070a9/cmake/ConfigFileSetting.cmake#L105

[MRG] FIX tests for NEURON v8

---

doc/Makefile
doc/whats_new.rst
examples/plot_simulate_gamma.py
hnn_core/cell.py
hnn_core/cell_response.py
hnn_core/cells_default.py
hnn_core/drives.py
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/tests/test_cell.py
hnn_core/tests/test_cell_response.py
hnn_core/tests/test_cells_default.py
hnn_core/tests/test_network.py
hnn_core/viz.py

closes #316 
The goal here is to create an API for users to adjust biphysics and synapse properties as they do in HNN-GUI.

[MRG] add method for updating cell biophysics from Network instance

---

doc/api.rst
doc/whats_new.rst
examples/plot_connectivity.py
examples/plot_firing_pattern.py
examples/plot_simulate_alpha.py
examples/plot_simulate_evoked.py
examples/plot_simulate_gamma.py
examples/plot_simulate_mpi_backend.py
examples/plot_simulate_somato.py
hnn_core/__init__.py
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/tests/conftest.py
hnn_core/tests/test_dipole.py
hnn_core/tests/test_mpi_child.py
hnn_core/tests/test_network.py
hnn_core/tests/test_parallel_backends.py
hnn_core/tests/test_viz.py
hnn_core/viz.py

At long last we're here! This PR is meant to flush out the API for modifying and visualizing the connectivity now that it has been decoupled from `network_builder.py` (#276), and the data structure is lightweight and interpretable (#313). 
Thanks to @jasmainak's suggestion to store separate connection types as objects, there is now a very clean path towards modifying existing connections. To demonstrate, this PR enables modification of existing connections with `net.connectivity[idx].update_probability(0.5)`. I have additionally added a `probability` argument to `net.add_connection`.
Here are my currently planned functions to add:
- `net.connectivity[idx].plot` which will produce a "checkerboard" to visualize connections
- `net.connectivity[idx].update_srcs` and …

[MRG] Add functions to modify and visualize connectivity

---

doc/whats_new.rst
hnn_core/cell.py
hnn_core/network_builder.py

[MRG] MAINT: remove move_to_pos

---

doc/api.rst
doc/whats_new.rst
examples/plot_connectivity.py
hnn_core/cell.py
hnn_core/network.py
hnn_core/tests/test_viz.py
hnn_core/viz.py

This has been on the to-do for awhile. I've added a function to visualize the connectivity weights so that the gaussian decay with distance is visible. Since gids are arranged in a grid, it produces some interesting repeating patterns: 
I still need to add some quick smoke tests, but I am satisfied with the current implementation of the function and definitely ready for some reviews.

[MRG] Add function to visualize connectivity weights

---

doc/whats_new.rst
hnn_core/network.py
hnn_core/tests/test_drives.py
hnn_core/tests/test_network.py

Closes #349. Turns out that it was a problem with setting `cell_specific=False` in `net._create_drive_conns`, Since the `drive_conn` dictionary is created prior to looping over cell types, all of the cell types share the same dictionary. Just added a `.copy()` to resolve the issue.

[MRG] Fix net.add_bursty_input() weight updating

---

doc/whats_new.rst
hnn_core/cell.py
hnn_core/drives.py
hnn_core/network.py
hnn_core/params.py
hnn_core/tests/test_network.py

Closes #347 
For the add_tonic_bias() method in the network class in network.py, I changed the T arg to tstop. In the method, I replaced all the T instances with the new tstop arg.
The _add_drives_from_params(net) function in drives.py calls the add_tonic_bias() method; thus I changed the args to match my changes to add_tonic_bias().
I didn't find any other instances where the add_tonic_bias() method was used so it should be fixed.

[MRG]: Better argument names for add_tonic_bias()

---

doc/Makefile
examples/plot_connectivity.py

Some tweaks to the connectivity example and a convenience option in the makefile to build individual files. Just do:
```sh
$ PATTERN=plot_connectivity make html_dev-pattern
```
@ntolley I see:
there is a grayscale colorbar and "Weight" written next to it. Isn't this incorrect? It should be probability? But I'd leave out the colorbar altogether for this kind of plot ...
also the filtering function we talked about would be really useful for a complete API. Then we can imagine doing:
```py
$ net.clear_connectivity(conn_idxs)
```
and then adding a modified connection. That would make this example less contrived I suppose?

[MRG] DOC: improve connectivity example

---

hnn_core/cell.py
hnn_core/tests/test_cells_default.py

Closes #330 by adding a test to check `sec.L` matches the difference in `sec.z3d(1) - sec.z3d(0)`.
I added a few lines to `Cell` based on the [NEURON docs for `pt3dadd`](https://nrn.readthedocs.io/en/latest/python/modelspec/programmatic/topology/geometry.html?highlight=pt3dadd#pt3dad):
```python
h.pt3dconst(0, sec=sec)
...
h.define_shape()
```

[MRG] check section lengths match L-parameter

---

doc/whats_new.rst
hnn_core/dipole.py
hnn_core/tests/test_dipole.py

Closes #306
Fixed bug in average_dipoles() function in dipole.py, now allowing for computation of an average even for n_of_1 simulation. I essentially had the function just return the first and only dipole instance in the input parameter dipoles list.
For n_of_1 trials, I decided to also include a message to let users know that when calling an average on a sample size of 1, they should consider simulating at least two trials to properly produce an average.

[MRG] Fix average_dipoles to allow for one trial

---

doc/whats_new.rst
hnn_core/cell_response.py
hnn_core/tests/test_cell_response.py

Since this is an obvious 1-line fix that allows us to read legacy spk.txt files, unless there are any objections, I don't think we need to add a test here.

[MRG] BUG: read_spikes wasn't returning updated CellResponse instance

---

doc/whats_new.rst
examples/howto/plot_connectivity.py
hnn_core/tests/test_viz.py
hnn_core/viz.py

Not sure if this is useful, could get some feedback before working more on it ...
closes #375

[MRG] ENH: interactive connectivity

---

doc/api.rst
doc/whats_new.rst
examples/howto/plot_connectivity.py
examples/howto/plot_firing_pattern.py
examples/howto/plot_record_extracellular_potentials.py
examples/howto/plot_simulate_mpi_backend.py
examples/workflows/plot_simulate_alpha.py
examples/workflows/plot_simulate_beta.py
examples/workflows/plot_simulate_evoked.py
examples/workflows/plot_simulate_gamma.py
examples/workflows/plot_simulate_somato.py
hnn_core/__init__.py
hnn_core/cells_default.py
hnn_core/network.py
hnn_core/network_models.py
hnn_core/tests/conftest.py
hnn_core/tests/test_dipole.py
hnn_core/tests/test_extracellular.py
hnn_core/tests/test_mpi_child.py
hnn_core/tests/test_network.py
hnn_core/tests/test_parallel_backends.py
hnn_core/tests/test_viz.py

Closes #384 #111 
the API has moved since #275 . Starting a new PR.
Todos
------
~~- [x] update examples~~
~~- [ ] replace `dpl.txt`~~
~~- [x] update `param` files from https://www.dropbox.com/sh/ynpcwiw3t627ox8/AADkcq-AobmaATiowXKoVm4Wa?dl=0~~
Edit: Saving updated examples for separate PR. The goal of this PR is to just introduce a function to load the calcium model.

[MRG] ENH: calcium dynamics

---

hnn_core/viz.py

Closes #396
https://github.com/jonescompneurolab/hnn-core/blob/40b07726a747c336debfe3a2683ee1607391a75d/hnn_core/viz.py#L450
`plot_cells()` takes the Network object as a param, not the NetworkBuilder. Fixed the docstring to reflect this.

DOC: Fixes plot_cells() param doc string by replacing NetworkBuilder with Network

---

doc/whats_new.rst
examples/howto/plot_connectivity.py
hnn_core/check.py
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/tests/test_network.py
hnn_core/viz.py

This PR turned into a gauntlet of if/else statements so I'd definitely love some input if you guys see a place to simplify. In any case I am quite happy with the functionality and to my eyes everything seems to be working correctly. The API works as follows:
```py
net.pick_connection(src_gids='L2_pyramidal', target_gids=[0, 1, 2])
```
Will return the index of any connections in `net.connectivity` that _both_ contain L2 pyramidal cells as `src_gids`, and `[0, 1, 2]` in the set of `target_gids`. 
```py
net.pick_connection(receptor=['nmda', 'ampa'])
```
Will return all connections that have _either_ NMDA or AMPA synapses.
More succinctly, supplying a list to a single parameter corresponds to a `logical_or`, whereas supplying multiple parameters corresponds to a `logical_and` across the …

[MRG] ENH: Add function to search for specific connections

---

hnn_core/extracellular.py

The gather-method of the PtrVector `_nrn_imem_ptrvec` causes
a segmentation fault when `simulate_dipole(net)` is called
multiple times within the same python/ipython process. This
happens naturally in loops. The Neuron documentation is vague
about the update-method, but other OSS (e.g. NetPyNE) tools
use it.
See discussion in #370 where this bug was identified. Note that I haven't been able to create a test that recreates the segmentation fault using the "reduced" parameter set!

[MRG] ptr_update_callback fixes segfaults

---

hnn_core/network.py

I got a little confused looking at the code because the docstring claimed to accepts a string value for `n_drive_cells`. Of course this wouldn't happen since it's called from `Builder...

[MRG] fix docstring in _create_drive_conns

---

doc/whats_new.rst
hnn_core/drives.py
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/params.py
hnn_core/tests/test_drives.py
hnn_core/tests/test_network.py
hnn_core/tests/test_parallel_backends.py

This is a very draft version, @cjayb do you have any objection to this kind of direction?
I think it will depend on some changes @ntolley is making in #348

[MRG+1] unify cell connectivity and drive connectivity

---

hnn_core/extracellular.py
hnn_core/network_builder.py
hnn_core/tests/test_extracellular.py

This fixes the issues met in #370 #401 #408 related to extracellular potential calculations, where repeated simulations in the same python process caused segmentation violations.
The test in  c8f60aa fails in `master` because the buggy implementation causes the simulation time to start to creep. The 5% limit is quite strict and may need to be relaxed (leading to a longer test time). I could not generate segfaults on less-than-complete networks, so this was the best compromise I could come up with. EDIT: **this will be removed as it's not a unit test**. However, the code demonstrates a simple way to catch the underlying problem.
~The fix in  b6ee4fc just moves the callback-function out of the `_ExtracellularArrayBuilder` class/object. Now `extra_scatter_gather` and …

[MRG] allow multiple extracellular simulations in single python process

---

doc/whats_new.rst
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/tests/conftest.py
hnn_core/tests/test_network.py

Issues arose due to the fact that simulations that attach Neuron objects (in `Network.cells`) to a `Network` instance can't be passed back to the user or instantiated a second time (i.e., when running serial simulations on the same network instance) when parallelizing across multiple processes or jobs. This fixes the problem by removing `Network.cells` altogether.
closes #432
closes #434

[MRG] remove cells from the Network class

---

doc/whats_new.rst
examples/howto/plot_firing_pattern.py
examples/howto/plot_simulate_mpi_backend.py
examples/workflows/plot_simulate_alpha.py
examples/workflows/plot_simulate_beta.py
examples/workflows/plot_simulate_evoked.py
examples/workflows/plot_simulate_gamma.py
examples/workflows/plot_simulate_somato.py
hnn_core/dipole.py
hnn_core/drives.py
hnn_core/network.py
hnn_core/network_models.py
hnn_core/params.py
hnn_core/tests/test_dipole.py
hnn_core/tests/test_drives.py
hnn_core/tests/test_network.py
hnn_core/tests/test_viz.py

Closes #410. Thanks to #369, this task is quite straightforward. The goal of this PR is to add a probability argument to the drives API, such that `net.add_evoked_drive(..., probability=0.5)` randomly removes half the drive connections, and only a subset are actually targeted by the drive. Additionally, the probability argument should also accept a dictionary which specifies probabilities for each individual connection (same was the weight and delay arguments).
After completing this, I think the final task for fully merging the drives and connection API's is enabling the manual targeting of `target_gids`, but let's leave that as a topic of discussion for the upcoming retreat ;).

[MRG] Add probability arguments to drives API

---

doc/whats_new.rst
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/tests/test_drives.py

Closes #457 and #455. Fairly simple adjustments, adding `simulate_dipole()` inside `test_drives.py` revealed both problems.

[MRG] MAINT: Fix bugs from inputs to drives API

---

doc/whats_new.rst
hnn_core/cell_response.py
hnn_core/tests/test_cell_response.py

I was just trying to use this with Michael Hines and realized that it throws an error for a regular string. I think it should instead append the trial index instead of throwing an error.

[MRG] make cell_response.write more robust

---

LICENSE

[GSoC requires](https://developers.google.com/open-source/gsoc/faq#what_are_the_eligibility_requirements_for_a_mentoring_organization) using an [open source initiative approved license](https://opensource.org/licenses). I think we agreed in previous discussions that we will settle with BSD-3 for hnn-core but a more restrictive license for additions on top of hnn-core, for example if there was something built using SBI. The switch to BSD-3 was ultimately never made but I think this is a good moment to do.
@stephanie-r-jones are you okay with this? A quick merge would be appreciated @stephanie-r-jones @ntolley @rythorpe as it will allow me to move forward the application in PSF

Use BSD-3 license

---

.mailmap

closes #440 
let's hope this fixes the problem with @blakecaldwell being shown as having only one commit

[MRG] MAINT: mailmap

---

doc/whats_new.rst
examples/howto/plot_firing_pattern.py
examples/howto/plot_simulate_mpi_backend.py
examples/workflows/plot_simulate_alpha.py
examples/workflows/plot_simulate_beta.py
examples/workflows/plot_simulate_evoked.py
examples/workflows/plot_simulate_gamma.py
examples/workflows/plot_simulate_somato.py
hnn_core/drives.py
hnn_core/network.py
hnn_core/network_models.py
hnn_core/params.py
hnn_core/tests/test_drives.py

closes #454 
Examples: https://2122-168215891-gh.circle-artifacts.com/0/html/index.html
This PR makes the simulation output agnostic of the order in which the drives are added. The seeds of the drives have to be adjusted for the new scheme.
Another problem that is fixed in this new scheme is that negative seeds are no longer allowed (as in numpy and other software). Earlier a negative seed would be okay because the final seed used would be `event_seed + gid` and `gid` may start from a large positive number instead of 0

[MRG] Gid offset

---

doc/whats_new.rst
examples/howto/optimize_evoked.py
hnn_core/network.py
hnn_core/network_models.py
hnn_core/optimization.py
hnn_core/tests/test_drives.py
hnn_core/tests/test_optimization.py

Makes the following improvements to the `optimize_evoked()` routine:
closes #268

[MRG] minor optimization workflow issues

---

doc/whats_new.rst
hnn_core/cell_response.py
hnn_core/tests/test_viz.py
hnn_core/viz.py

Closes #471 Implements the ability to filter out specific trials either through lists or integers:
```py
net.cell_response.plot_spikes_raster(trial_idx=0)
net.cell_response.plot_spikes_raster(trial_idx=[0, 1])
```

[MRG] Add ability to index individual trials when plotting rasters/histograms

---

doc/whats_new.rst
examples/workflows/plot_simulate_alpha.py
examples/workflows/plot_simulate_beta.py
hnn_core/dipole.py
hnn_core/tests/test_dipole.py
hnn_core/tests/test_viz.py
hnn_core/viz.py

To address #473 , we add an extra line plot when the `dpl` in `plot_dipole` is a list. All individual trial lines are colored gray while the average one is green. And if the dpl is a `Dipole` instance, the single trial will be green. 
Below is the current behavior:
Also, I changed the way to turn `dpl` into a list, as a function should not modify its parameters especially when the purpose is to draw something. Because the user may expect the `dpl` to stay the original type after multiple calls of the visualization function (for reasons like refining styles).

[MRG] Add average dpl plot

---

CONTRIBUTING.rst

The current link in the [contributors guide](https://github.com/jonescompneurolab/hnn-core/blob/master/CONTRIBUTING.rst) for the [parallel backend installation instructions](https://github.com/jonescompneurolab/hnn-core/blob/master/doc/parallel.rst) points [here](https://jonescompneurolab.github.io/hnn-core/parallel.html). Since we don't currently compile the contributors guide via sphinx on the stable branches, the updated link here points toward whichever 'parallel.rst' file is on the master branch.

[MRG] DOC: update link to parallel.rst in contributors guide

---

.github/workflows/unit_tests.yml
MANIFEST.in
README.rst
binder/postBuild
binder/requirements.txt
hnn_core/gui.py
hnn_core/gui/gui.py
hnn_core/gui/hnn_widget.ipynb
hnn_core/params.py
hnn_core/tests/test_gui.py
hnn_widget.ipynb
setup.py

Here is a demo of the GUI with ipywidgets. 
[Try on Mybinder!!!](https://mybinder.org/v2/gh/jasmainak/hnn-core/hnn_gui?urlpath=voila%2Frender%2Fhnn_widget.ipynb)
Some advantages of this approach:
- Easier to maintain. We can probably get 95% of the functionality with 1000 lines of clean code as opposed to maintaining [8000 lines](http://line-count.herokuapp.com/jonescompneurolab/hnn) of messy code
- Easy to install/deploy in classroom environment
- You can easily add new features (e.g., Nick's work related to connectivity). 
- Ability to spin up HNN from the mobile and host a demo on Brown website using JupyterHub :-)
- Potential to integrate with MNE source localization ['notebook' backend](https://github.com/mne-tools/mne-python/blob/4a0ff5ca675f2f97838c7941a015c6ef8e59f12e/mne/viz/backe …

[MRG + 1] ENH: try making HNN GUI with ipywidgets

---

README.rst
doc/contributing.rst
examples/howto/plot_record_extracellular_potentials.py
examples/workflows/plot_simulate_alpha.py
examples/workflows/plot_simulate_evoked.py
hnn_core/cell_response.py
hnn_core/network.py
hnn_core/viz.py

This is a quick follow-up to #483, based off of a prior [suggestion](https://github.com/jonescompneurolab/hnn-core/pull/483#issuecomment-1179569301) given that our contributing guide is not currently compiled along with the rest of the `doc/` directory. Note that instead of referencing `hnn-core/contributing.rst` in `hnn-core/doc/index.rst`, however, I've just moved the actual contributing guide file to `hnn-core/doc/contributing.rst`.
Also, all links in the docs to the parallel backend instructions and contributing guide now reference the latest stable version.

[MRG] DOC: build parallel.rst and contributing.rst with sphinx

---

doc/whats_new.rst
hnn_core/cell.py
hnn_core/tests/test_cell.py
hnn_core/viz.py

[MRG] Make cell morphology plots reflect actual cell size

---

README.rst

I just noticed that our test badge in README.rst was still referencing Travis. I've now updated it to reference our CI with GH Actions. Here's what our compiled README.rst looks like now:

[MRG] DOC: update badges in README.rst

---

doc/whats_new.rst
hnn_core/network.py
hnn_core/tests/test_network.py

Closes #514. Fixes logic in `pick_connection()` where certain edge cases don't return an empty list even when the searched connection doesn't exist.

[MRG] BUG: Fix edge case with non existing connections in `pick_connection()`

---

.circleci/config.yml
.github/workflows/linkcheck.yml
doc/api.rst
hnn_core/gui/__init__.py
hnn_core/gui/gui.py
hnn_core/gui/hnn_widget.ipynb
hnn_core/tests/test_gui.py

Try to refactor the GUI code in an OP manner.

[MRG] GUI refactoring

---

doc/whats_new.rst
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/network_models.py
hnn_core/tests/test_drives.py
hnn_core/tests/test_network.py

This PR adds checks inside `net.add_connection` to ensure the valid `loc`, `receptor`, `target_type` combinations are specified. Depending on the definition of the cell, certain combinations will break during `simulate_dipole`. For example, pyramidal cells do not have `ampa` synapses so if the user accidentally defines one with `net.add_connection`, then the simulation will break.
While writing this I am realizing there are some issues with how things are organized internally. At the moment we support `proximal`, `distal`, and `soma` as valid location arguments. However, `soma` is handled a bit strangely since it is not defined in the `sect_loc` attribute but still passes as a valid location because it has defined synapses:
https://github.com/jonescompneurolab/hnn-core/blob/4fde7c6f3058cba …

[MRG] Add warnings for invalid connections

---

hnn_core/network_builder.py

This adds support for Apple Silicon ("M"-series, 64-bit ARM architecture). Tested on a system running 
- M1 Pro system with 8 cores (6 "performance" and 2 "efficiency" cores)
- [miniforge](https://github.com/conda-forge/miniforge) instead of vanilla `conda` (for the `arm` support)
- Python 3.10 (got picked up by `conda`, not sure by which dependency
(Almost) all tests pass locally. MPI example is working fine, but `test_parallel_backends.py` chokes when oversubscribing (will create a separate PR).
Support for Mx Macs in `hnn-core` might need to be flagged as 'experimental'?

[MRG] ADD support Apple Silicon (arm64) NEURON mechs

---

hnn_core/parallel_backends.py
hnn_core/tests/test_parallel_backends.py

This is a continuation of #538 (first commit is identical, can be rebased trivially), where I try to figure out why the oversubscribe-test fails in `test_parallel_backends`.
The second commit is part of the solution: fixes `TestParallelBackends.test_terminate_mpibackend`, which fails with 
```python
expected_string = "Child process failed unexpectedly"
>       assert expected_string in record[0].message.args[0]
E       AssertionError: assert 'Child process failed unexpectedly' in 'isSet() is deprecated, use is_set() instead'
```
However, the second one is more thorny (in `TestParallelBackends.test_run_mpibackend_oversubscribed`):
```python
command = ['mpiexec', '--use-hwthread-cpus', '--oversubscribe', '-np', '12', 'nrniv', ...]
...
if not proc.returncode == 0:
>           raise …
```

[MRG] attempt to fix MPI support on Apple Silicon

---

doc/whats_new.rst
examples/howto/plot_simulate_mpi_backend.py
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/parallel_backends.py
hnn_core/tests/test_parallel_backends.py

closes #406 
Finally figured it out. Our `MPIBackend` unit tests use a reduced network model to speed things up. This revealed a rare edge case that only shows up on machines with a large number of logical cores, where more MPI threads were created than there were neurons contributing to the dipole. When `NetworkBuilder().aggregate_data()` then tried to add up and reduce its NEURON data instances across both intra-rank and inter-rank neurons, it hung due to to a mismatch between `h.Vector()` sizes.

[MRG] BUG: fix elusive MPI runtime error in tests

---

doc/whats_new.rst
hnn_core/dipole.py
hnn_core/mpi_child.py
hnn_core/network_builder.py
hnn_core/parallel_backends.py
hnn_core/tests/test_mpi_child.py

This is just a quick follow-up to #545 where I found it hard to trace how far a simulation had progressed before failing due to where/how the print messages were placed in `parallel_backend.py` and `network_builder.py`. I also took the liberty of fixing a few nitpicky typos in some docstrings.

[MRG] MAINT: improve parallel backend and runtime messages

---

hnn_core/gui/gui.py
setup.py

Closes #552. Glad to see it wasn't our fault! From what I can tell the last `ipywidgets` update broke the `.set_title()` functionality for widgets. Probably related to [this](https://github.com/jupyter-widgets/ipywidgets/pull/3477) This is resolved by instantiating the widgets with all the titles at the outset using a `tuple`. 
Not totally sure I understand the problem yet, but in any case these changes resolve the errors associated with titles and works for both versions.

[MRG] MAINT: Fix gui tests

---

doc/whats_new.rst
hnn_core/check.py
hnn_core/network.py
hnn_core/tests/test_network.py

Highly specific but unfortunate oversight. Currently `pick_connection()` fails when attempting to search connection indices when specifying the src or target gids as a list of cell types. Minimal reproducible example:
```py
from hnn_core import jones_2009_model, pick_connection
net = jones_2009_model()
pick_connection(net, src_gids=['L2_basket', 'L5_basket'])
```
The code fails because `pick_connection()` verifies string inputs using `_check_gids()`. There is a condition in `_check_gids()` that ensures all of the gids are of the same type, this is important for `net.add_connection`, but makes the use above fail.
I've just added the boolean flag `_check_gids(same_type=True)` to allow switching between these conditions.

[MRG] BUG: Allow `pick_connection()` to accept list of cell types

---

doc/whats_new.rst
hnn_core/dipole.py
hnn_core/tests/test_drives.py

[MRG] add drive warnings

---

doc/whats_new.rst
examples/howto/plot_firing_pattern.py
hnn_core/cell.py
hnn_core/cell_response.py
hnn_core/dipole.py
hnn_core/network_builder.py
hnn_core/parallel_backends.py
hnn_core/params_default.py
hnn_core/tests/conftest.py
hnn_core/tests/test_cell_response.py
hnn_core/tests/test_cells_default.py
hnn_core/tests/test_dipole.py
hnn_core/tests/test_extracellular.py

This is an enhancement I've been meaning to add for awhile. Not sure if this is going to cause a lot of problems in terms of data transfer, but we'll see!
The way things are currently written are very redundant with the somatic recording functionality. Once I know this is working, the `record_vsoma` and `record_isoma` options to `simulate_dipole` can use the same code as here by restricting the section names considered to only be the `'soma'`.

[MRG] Add ability to record voltages and currents from all sections

---

README.rst

The brackets in zsh have an alternative use by default and require colons for the pip install

[MRG] DOC: correct macOS pip install instructions for hnn-gui

---

README.rst
setup.py

Closes #585 
Restricts voila to versions <=0.3.6 to prevent javascript error when rendering GUI

[MRG] MAINT: Restrict voila version

---

hnn_core/tests/test_cell_response.py
hnn_core/tests/test_dipole.py
hnn_core/tests/test_extracellular.py
hnn_core/tests/test_gui.py
hnn_core/tests/test_viz.py

Closes #540 
Adds `plt.close('all')` at the end of unit tests that create plots

[MRG] MAINT: Close figures in unit tests

---

hnn_core/viz.py

This is pretty straightforward and will hopefully reduce the number of warnings that get produced when building docs or running examples.
closes #486

[MRG] MAINT: define dtype=object for ragged nested ndarrays in viz.py

---

doc/whats_new.rst
hnn_core/drives.py
hnn_core/tests/test_drives.py

Found by @wagdy88, adding an evoked drive with only NMDA weights threw an error. Solution was fixing a typo in `_get_target_properties()`

[MRG] BUG: Allow adding drives with just NMDA weights

---

doc/whats_new.rst
hnn_core/drives.py
hnn_core/tests/test_params.py

@rythorpe @jasmainak I think I figured out the issue with creating a network from a params file when `legacy_mode=False`. In the file there are "dummy drives" where the `tstart` comes after `tstop` so that the drive never occurs in the simulation.
I just added a conditional statement to skip over these drives when they come up, if you see a more elegant solution let me know!

[MRG] Fix legacy param reading for legacy_mode=False

---

doc/whats_new.rst
hnn_core/tests/test_dipole.py
hnn_core/viz.py

Closes #511 
I made changes in plot_dipole function in viz.py to type of argument 1. Iteration is used when a list of dipoles is passed. I have included a test in test_dipole.py where [dipole, integer] is passed as an argument to plot_dipole() and the appropriate error message is checked using pytest.

[MRG] ENH: Added instance type check for plot_dipole function and also a test for it

---

doc/whats_new.rst
hnn_core/cell.py
hnn_core/tests/test_viz.py
hnn_core/viz.py

I'd like to make a few additions to the visualization functions that will make animating HNN simulations more straight forward. The main change is allowing a custom color for each cell section in `Cell.plot_morphology` like so:
```py
from hnn_core import jones_2009_model
net = jones_2009_model()
sections = list(net.cell_types['L5_pyramidal'].sections.keys())
section_color = {sect_name: f'C{idx}' for idx, sect_name in enumerate(sections)}
net.cell_types['L5_pyramidal'].plot_morphology(color=section_color)
```
The other addition will be a `plot_network_morphology` function (alternate name suggestions are appreciated!) that simply calls `Cell.plot_morphology` and places the cells in their appropriate 3D position.
With these two functions the code to make animations is pretty slim and could …

[MRG] ENH: Custom section colors in Cell.plot_morphology

---

doc/whats_new.rst
hnn_core/__init__.py
hnn_core/cell_response.py
hnn_core/tests/test_cell_response.py
setup.py

- Wrote a method `write_hdf5()` for `cell_response`
- Wrote a method `read_spikes_hdf5()` to read a hdf5 file and instantiate a `cell_response` object
- A small test for checking the working for read\write method
`pip install h5io --upgrade` required for using h5io

[MRG] Added read/write methods and tests for cell response

---

doc/whats_new.rst
examples/howto/plot_connectivity.py
hnn_core/drives.py
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/tests/test_network.py

fixes #641 
I'm pretty sure the root of the bug was due to inconsistent ordering when looping over unordered [`set`](https://docs.python.org/3/library/stdtypes.html#set) elements. There are multiple places in `Network` and `NetworkBuilder` where `set` instances were used to populate ordered lists that influence the mapping of artificial cell gids -> network gids (i.e., even though the seeding behavior and drive spike times were perfectly consistent). My general strategy here was to remove ambiguity whenever possible, so there are some more maintenance-oriented modifications that simplify, convert, or make explicit certain ordered objects.

[MRG] BUG: fix inconsistency in seeded simulation output

---

doc/whats_new.rst
hnn_core/optimization.py
hnn_core/tests/test_cell_response.py
hnn_core/tests/test_dipole.py
hnn_core/tests/test_optimization.py

The goal here is to fix a few minor bugs that have popped up in master branch due to updates in dependencies. The biggest one revealed a bug on our end (as the title states), but the others were caused by an update in flake8 and a divergence between the object returned by pytest's legacy tmpdir ([`py.path.local` instance](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html#the-tmpdir-and-tmpdir-factory-fixtures)) and what h5py expects to read from / write to (a str specifying a path or pathlib.Path instance).

[MRG] BUG: objective function in optimization.py should return a scalar

---

hnn_core/drives.py
hnn_core/tests/test_drives.py

Closes #668.
Added "Please delete the L5_basket part from the code." to the error message.

[MRG] Update error message for adding drives

---

hnn_core/gui/_viz_manager.py
hnn_core/tests/test_gui.py

- Refactored GUI color cycling be compatible with matplotlib 3.8.x deprecation of `ax._get_lines.prop_cycler`. Substituted with  `ax._get_lines.get_next_color()`.
- Tested with older versions matplotlib==3.5.3 and 3.7.4 to make sure the plots still work.
closes #694 #688

[MRG] GUI dipole plot bug. 

---

.circleci/config.yml
README.rst
hnn_core/gui/_viz_manager.py
hnn_core/gui/gui.py
hnn_core/tests/test_gui.py
setup.py

**Completed**
* Removed pinning of older versions ipywidgets, ipympl, and voila. Set a requirement for ipywidgets >=8.1.1, because of breaking changes to v8.x. 
* Updating to the latest versions resolved js errors that were previously preventing the GUI from rendering, which was the impetus for pinning versions #585 #586. 
* Addressed some [ipywidgets 8.x API changes](https://ipywidgets.readthedocs.io/en/latest/user_migration_guides.html) that prevented GUI composition, running simulations, and plotting. 
* Implemented new methods of assigning titles and children to collection widgets (Tabs and Accordion). ~~Though only to the scope of what was causes crashes with what I was testing (composition and simulation launch).~~ There could be more areas were it should be updated. 
* Linking of …

[MRG] Update GUI to latest version of ipywidgets and voila

---

.circleci/config.yml
.github/workflows/linkcheck.yml
.github/workflows/unit_tests.yml
.github/workflows/windows_unit_tests.yml
doc/contributing.rst
doc/whats_new.rst
setup.py

This is a small PR to improve the classification & organization of extra dependencies. The key benefits to this change are:
1. Streamlines developer dependencies install 
- Contributors only need to run `pip install -e '.[dev]'`, to get all the dependencies for joblib, GUI, test, docs generation.
2. Installation of dependencies for Github runners uses the dependencies specified by the setup file.
- Prevents discrepancies between package versions specified in the setup file and workflow yml files 
- We don't have to remember to change dependency specifications in multiple files
*Note:*
- The mpi4py was left out of the dependency group because it was causing issues in tests when added to the `parallel` group. So developers will still need to manually install mpi4py and openmpi as …

[ENH] Dev extras

---

doc/whats_new.rst
hnn_core/network.py
hnn_core/network_models.py
hnn_core/tests/conftest.py
hnn_core/tests/test_dipole.py
hnn_core/tests/test_extracellular.py
hnn_core/tests/test_general_optimization.py
hnn_core/tests/test_mpi_child.py
hnn_core/tests/test_network.py
hnn_core/tests/test_optimize_evoked.py
hnn_core/tests/test_parallel_backends.py
hnn_core/tests/test_viz.py

As discussed in #704, we've realized that it is necessary to have an explicit API fro defining the size of the network object. Previously this was done in a hacky way by directly editing the `params` object. The proposed API here is 
```py
net = jones_2009_model(mesh_shape=(10, 10))
```

[MRG] ENH: Add ability to define cell grid dimensions

---

hnn_core/tests/test_gui.py

Fixes issue #697 
- added check for data on axes in `test_gui.py`

[MRG] Added data check on axes in `test_gui.py`

---

hnn_core/gui/_viz_manager.py
hnn_core/gui/gui.py
hnn_core/tests/test_gui.py

- Adding function to query if the data is a simulation or loaded from a file
- Reorganizing the compare visualization tab
- Adding scale and smooth factors float widgets
- Fixing logic to apply the new parameters to the plots
solves #717

[MRG] Fix dipole plot scale and smooth factors 

---

doc/whats_new.rst
hnn_core/network.py
hnn_core/tests/test_network.py

This fix resolves the bug discussed in #734 where the `pick_connection` function was picking incorrect connections. This was discovered when the function was tasked to pick cell connections in a Network where only drive connections were configured. The function still selected drive connections instead of returning an empty list. 
**Changes** 
1. pick_connection
i. Return empty list return whenever `inner_set` search is empty
ii. Prevent doing searches for arguments the user doesn't ask for (forwarding kw arguments to search loop)
iii. Refactor 
2. tests
i. Added test for searching for a cell connection in a network with only drives configured
closes #734

[MRG] Fix pick connection

---

doc/whats_new.rst
hnn_core/tests/test_viz.py
hnn_core/viz.py

Closes #735 
- Added check for invalid Axes object in `plot_cells` function, raises an error if found.

 [MRG] Fix: Added Axes object check in `plot_cells`

---

README.rst

Removed ipywidgets version and added note pointing to GUI installation section.
Discussed in #747

Remove ipywidgets version number from readme 

---

doc/whats_new.rst
hnn_core/cell_response.py
hnn_core/tests/test_cell_response.py
hnn_core/viz.py

Closes #186
- Enhance `plot_spikes_hist()` function with kwargs options

[MRG] ENH: Added `kwargs` options to `plot_spikes_hist`

---

doc/gui/tutorial_erp.ipynb
doc/whats_new.rst
hnn_core/gui/_viz_manager.py
hnn_core/gui/gui.py
hnn_core/tests/test_gui.py

- Added plot sets to the Layout templates
- Added logic to 'Make Figure' button to handle data depended layouts 
solves #711

[MRG] Added plot sets functionality

---

.github/workflows/codespell.yml
.github/workflows/linkcheck.yml
.github/workflows/unit_tests.yml
.github/workflows/windows_unit_tests.yml

Runners were no longer finding the conda base version preventing gh runners to build. 
- Updating the setup-miniconda line to version 3 seemed to fix the problem.  
- Updated the checkout action to v4. 
- Changed fetch-depth to 2 because it was stalling on codecov step on linux runners. [source](https://github.com/codecov/codecov-action/issues/190)
- Updated to use codecov upload action v4 instead of shell command
[setup-miniconda](https://github.com/conda-incubator/setup-miniconda/releases)
[checkout](https://github.com/actions/checkout/releases/tag/v4.1.4)

[MRG] Update GitHub actions

---

.github/workflows/unit_tests.yml
.github/workflows/windows_unit_tests.yml

Reverting back to the bash uploader until the codecov upload action is corrected. See details in #760 and #759.
closes #760

Codecov upload revert

---

hnn_core/tests/test_gui.py

Refactored the GUI tests to improve speed. Running simulations is the largest contributor to runtime so this focused on shortening simulation time and number of simulations run. Was able to reduce runtime by more than half.
* Created a fixture with reduced tstop and dt for faster simulations. Used the fixture in applicable tests.
* Reduced unnecessary iterations where simulations were run multiple times.
_Previous_
_Refactored_

[MRG] Optimize GUI tests

---

doc/whats_new.rst
hnn_core/drives.py
hnn_core/network.py
hnn_core/tests/test_io.py
hnn_core/tests/test_network.py

- Refactor `network.add_tonic_bias` to accept a dictionary of cell types and their amplitudes.
- Changed how drivers create tonic inputs
- Adjusted unit tests to the new `network.add_tonic_bias` arguments

[REF]: Refactor network.add_tonic_bias

---

doc/api.rst
doc/whats_new.rst
examples/howto/plot_hnn_animation.py
hnn_core/cell.py
hnn_core/tests/test_viz.py
hnn_core/viz.py

Here's my first pass at creating a viz class that can be used to quickly render the full 3D network, as well as membrane potentials of individual sections. This is meant to be largely generic and flexible so that it can be co-opted for other purposes. I think the most interesting applications at the moment would be:
- Quickly generating animations of HNN simulations
- Embedding the 3D plot into the current ipywidgets GUI
The current strategy for the class is to do all of the heavy lifting at the initialization (namely creating the 3D object, and mapping the voltage recordings to the appropriate colors). For a quick demo, the code below can be run on my laptop on a single core in approximately 20 sec:
```py
from hnn_core import jones_2009_model, simulate_dipole
from hnn_core.network_models …
```

[MRG] NetworkPlot class to enable interactive visualizations and animations

---

doc/whats_new.rst
hnn_core/gui/gui.py
hnn_core/tests/test_gui.py

Wok on new Feature to add tonic input from in the GUI
Solves #715

[ENH] Added tonic input to GUI drivers tab

---

hnn_core/gui/gui.py

Just a quick fix on the load data button style.

MAINT: Fixed load data button size

---

README.rst
doc/governance.rst

Hi, I create a new governance structure .rst file and updated the README.rst to point to where the gh page will be hosted once published... I rendered the html files locally and they look good to me. I'm unclear on the process for posting the .html files generated...is there an Action that makes them automatically? is that a separate PR under the gh-pages branch? thx :)

[MRG] Add governance structure and update README

---

doc/whats_new.rst
hnn_core/cell_response.py
hnn_core/gui/gui.py
hnn_core/network.py
hnn_core/viz.py

Problem raised in #794 that numpy version 2.0.0 has deprecated `np.in1d()`

[MRG] Replace `np.in1d()` with `np.isin()`

---

README.rst

Linkcheck verifies the test badge URL is working. As we renamed the `unit_test.yml` workflow to `unix_unit_tests.yml `, the URL needs to be updated

[MAINT] Update README test badge's URL

---

.github/workflows/unix_unit_tests.yml
.github/workflows/windows_unit_tests.yml
hnn_core/gui/gui.py
hnn_core/tests/test_drives.py
hnn_core/tests/test_extracellular.py

For now we decided to test the 2 latest versions and oldest supported version of python on mac, Linux, and windows for all PRs. A full-matrix test of all supported python versions performed at a longer frequency is still being considered. 
This PR is aimed to fix incompatibilities found in the tests against python 3.11 and 3.12

[MAINT] Fixing Unit Tests for Python 3.11 and 3.12 support

---

dev_scripts/convert_params.py
doc/whats_new.rst
hnn_core/__init__.py
hnn_core/params.py
hnn_core/tests/test_io.py
hnn_core/tests/test_params.py

This changes the convert_to_hdf5 function to convert_to_json. 
* The function converts legacy flat json and param files to the new hierarchical json format. 
* It also adds network connectivity. By default it uses the Jones 2009 model for the connectivity but supports the other pre-defined network models. No network connectivity can be added by supplying None.
Question:
* Should the default be None instead of the Jones 2009 for adding network connectivity?

[MRG] Update legacy json and param conversion function for new json format

---

hnn_core/hnn_io.py
hnn_core/tests/test_io.py

Reading network configurations from hierarchical json with `read_drives=False` was only clearing the external_drives and not the drive connectivities in the network connectivity information. This fix corrects that issue.

[MRG] read_network_configuration not clearing drive connections

---

doc/conf.py
doc/gui/index.rst
doc/whats_new.rst
hnn_core/tests/test_viz.py
hnn_core/viz.py

Closes #658
- Updated `plot_spikes_raster` logic to always include all cell types.

[MRG] ENH: `plot_spikes_raster` to always include all cell types

---

doc/whats_new.rst
hnn_core/drives.py
hnn_core/network.py
hnn_core/tests/test_drives.py

Closes #414. Instead of incrementing a seed by +1 for each trial, the seed is incremented by the total number of cells in the network.

[MRG] Fix seeding for drive cell event times

---

doc/Dockerfile
doc/conf.py

closes #377 
Demo:
https://mybinder.org/v2/gh/jasmainak/hnn-core/fix_binder?filepath=dev/notebooks/auto_examples/workflows/plot_simulate_evoked.ipynb

[MRG] fix binder

---

.github/workflows/linkcheck.yml
doc/Makefile
doc/conf.py
setup.py

We no longer need these dependencies for building the documentation, removing to simplify the installation

MAINT: Remove nbspinx and pandoc

---

doc/whats_new.rst
hnn_core/network.py
hnn_core/tests/test_drives.py

This addresses issue #662 and includes a test for adding poisson drives to test_drives.py.
The test also yields an error with {"rate_constant" = 2, "cell_specific"=True, "n_drive_cells" = "n_cells"}, but not with {"rate_constant" = 2.0, "cell_specific"=True, "n_drive_cells" = "n_cells"}. I'll open a separate bug for this?
Test output:
```
event_times = np.array([])
if drive_type == 'poisson':
if target_type == 'any':
rate_constant = dynamics['rate_constant']
>           elif target_type in dynamics['rate_constant']:
E           TypeError: argument of type 'int' is not iterable
hnn_core/drives.py:284: TypeError
```

[MRG] Poisson drive tests and bug fix for #662

---

doc/whats_new.rst
hnn_core/network.py
hnn_core/tests/test_drives.py

Currently calling `net.clear_drives` does not update the `Network` correctly. This PR adds implements these updates and adds a quick test to ensure the updates are applied.
@gtdang feel free to merge when the checks are green!

[MRG] BUG: Update `gid_ranges` after using `clear_drives`

---

README.rst
doc/whats_new.rst
hnn_core/network.py
hnn_core/tests/test_drives.py

This fix addresses issue #816 and updates the test for adding poisson drives in test_drives.py with additional conditions to check

[MRG] fix for add_poisson_drive not working with int when cell_specific=True

---

README.rst

Added link to governance structure
Removed broken link to roadmap
Updated link in Bug Reports to point to Discussions instead of the Google Group

[MRG] Fix hnn-core homepage links

---

doc/gui/tutorial_erp.ipynb
doc/whats_new.rst
hnn_core/gui/gui.py
hnn_core/tests/test_gui.py

This is the work for the cell params feature for L2 and L5 pyramidal cell types

[MRG]: Add cell parameters in GUI

---

hnn_core/gui/gui.py
hnn_core/tests/test_gui.py

The simulations dropdown list was adding loaded data, and hnn-gui cant export non-simulated data.
solves #824

[MRG]: Fixed simulations dropdown list adding loaded data

---

hnn_core/params.py
hnn_core/tests/test_params.py

Updated the hierarchical json conversion script to prune nulled drives. Legacy param files had placeholders for several drives. If unused, values out of typical ranges were specified to null those drives. Typically this occurs when a start time is set greater than the stop time or if weights are set it negatives or 0s. The hierarchical json format will not include drives with bad parameters. 
Summary of Changes: 
* Added logic to remove drives that did not have at least 1 positive weight or had invalid _tstop_ and _tstart_ values. 
* Removed _model_template_ argument from `convert_to_json` and associated tests - After discussion that we are using this function internally to convert tutorial files. And they will all be the jones2009 model. 
**Questions**
1. Are the filters for nulled …

[MRG] Remove nulled drives during convert to hierarchical json function

---

hnn_core/gui/gui.py
hnn_core/tests/test_gui.py

Creates the ability to use local files for simulating GUI file uploads for unit-testing. Previously there was only the ability to load from URL sources. This will allow the use of local files so developers are not required an internet connection to run tests and to make use of default configuration files that are included in the repo.
Extracted from #808

[MRG] Simulate upload from local

---

hnn_core/gui/_viz_manager.py
hnn_core/tests/test_gui.py

This PR will fix #826 .  In the visualization tab, the simulation type dropdown list values are overwritten with simulation names, disabling the `data to compare` dropdown list and creating more bugs.
It is related to PR #543  and [this](https://github.com/jonescompneurolab/hnn-core/pull/543/commits/f6eaf0b0141256e6889f81a6b195c65dba7b68cf) commit

[MAINT] GUI -Fix Update simulation type dropdown list

---

hnn_core/hnn_io.py

Added `n_drives_cells` argument to `add_evoked_drive` in the `read_external_drive` function used when converting a network configuration file to Network.
split from #808

fix: missing n_drive_cells argument during configuration to Network conversion

---

hnn_core/gui/gui.py
hnn_core/tests/test_gui.py

Dictionaries that are nested within dictionaries are not updated with the update method. A recursive function was added to search for dictionary keys of nested dictionaries for updating. This is used for updating default values for GUI widgets. 
Changes:
* Added a recursive update function that will search nested dictionaries for keys to update
* Updated default values for poisson widget
split from #808

[MRG] Fix update gui default dicts

---

doc/whats_new.rst
examples/howto/optimize_evoked.py
examples/howto/optimize_rhythmic.py
hnn_core/optimization/__init__.py
hnn_core/optimization/general_optimization.py
hnn_core/optimization/objective_functions.py
hnn_core/tests/test_general_optimization.py

The goals are:
1. To be able to optimize parameters associated with rhythmic drives. The user sets the frequency bands and relative bandpower. In the example below, we wish to optimize power in the 9-11 Hz and 19-21 Hz bands in a ratio of 1 to 2 (i.e. twice as much power in the beta band as in the alpha band). 
```
optim = Optimizer(net, tstop=tstop, constraints=constraints,
set_params=set_params, obj_fun='maximize_psd')
optim.fit(f_bands=[(9, 11), (19, 21)], relative_bandpower=(1, 2), scale_factor=scale_factor,
smooth_window_len=smooth_window_len)
```
**Example output**
**Reversing the ratios**
```
optim.fit(f_bands=[(9, 11), (19, 21)], relative_bandpower=(2, 1), scale_factor=scale_factor,
smooth_window_len=smooth_window_len)
```
2. To allow the user to define `obj_fun` as a callable.

[MRG] Optimize rhythmic drives

---

hnn_core/tests/test_general_optimization.py

Closes #838 
Reduces test times by running smaller networks, less simulations iterations, and using shorter simulations
@gtdang I was able to run the optimization test in ~10 seconds on my local computer
I'm fairly certain the optimization examples aren't being built by circleCI (which would really blow up the run time) but I'll check that here

[MRG] Faster optimization tests

---

hnn_core/gui/gui.py

Removed connection probability assignment in `_init_network_from_widgets`
This was removed because there is not a probability widget. Also, just updating the probability value  does not update underlying gid pairs using the probability. A setter will have to be created for the assignment to update the appropriate connection properties. This is planned future work.

fix: GUI removed connection probability assignment 

---

hnn_core/gui/gui.py

The extra display call was not needed because the display is called within the function to render the cell params. Also the function it was wrapping had no return, thus causing a "None" to print to the console.

[MRG] fix: removed unnecessary display call

---

hnn_core/gui/gui.py

Added a confirmation message when connectivity or drives are loaded from file.

[MRG] GUI load confirmation message

---

hnn_core/gui/gui.py
hnn_core/tests/test_gui.py

The current implementation of the cell parameter widget skips over a compartment of L5 pyramidal cells
This PR correctly updates the compartment parameters, as well as improves testing to make sure the GUI network matches the API instantiated network

[MRG] make L5/L2 pyr have different geometry options in GUI

---

examples/howto/plot_batch_simulate.py
hnn_core/batch_simulate.py
hnn_core/tests/test_batch_simulate.py

A follow-up PR to extend and refine the functionality of `BatchSimulate`.
- Linkcheck fails when BatchSimulate is added to the hnn_core __init__
>  [To-do for me: figure out why linkcheck fails when BatchSimulate is added to the hnn_core __init__](https://github.com/jonescompneurolab/hnn-core/pull/811#issuecomment-2236774984)

[MRG] ENH: `BatchSimulate` Class

---

hnn_core/dipole.py
hnn_core/gui/gui.py
hnn_core/network.py
hnn_core/tests/test_dipole.py

As discussed in #767 we are going to use the following theme for the GUI:
Also @gtdang I added `dt` and `tstop` as private attributes to the network object. This will allow us to override the default `dt` and `tstop` to saved values when we load a network back in.

[MRG] Update GUI color

---

README.rst

The GUI image shows up on the github readme but not through sphinx, testing an alternate link to the file

[MRG] Fix GUI image link

---

doc/whats_new.rst
hnn_core/gui/_viz_manager.py
hnn_core/tests/test_gui.py

RMSE between simulations and data was not displaying on plots when simulations had multiple trials #858. The GUI was also behaving oddly where the plot was not being displayed #859.  Both issues are due to an error raised when attempting to average the dipoles when an average had already been calculated. 
**Work done:**
1. Fixed logic that was attempting to average dipoles. Created a function that will check and return if an average already exists, if not, it will calculate the average. 
2. Created a test to make sure a plot with the expected number of lines, legend items, and RMSE text is generated. 
closes #859 #858

[MRG] Fix GUI dipole data overlay

---

hnn_core/gui/gui.py

Removed debugging log messages for file saving that was overwriting the simulation output log when a simulation completed.

fix: GUI overwriting simulation output log

---

hnn_core/tests/test_gui.py

Updated `test_gui_run_simulation_mpi`.  The test was not actually testing if any dipoles were constructed. 
* Added assert that the dipole list is not empty 
* Updated the function to use the default network instead of gui test fixture (smaller mesh grid) because it was not working with MPI.  Presumably because the smaller network used in the fixture was not compatible with the parameterization of multiprocessing subprocess call.
*  We were encountering an error at the `h.finitialize` step of `network_builder`>`_simulate_single_trial` when using the fixture network. The error was within neuron: "NEURON: mindelay is 0 (or less than dt for fixed step method)".

[MRG] fix GUI MPI test

---

hnn_core/parallel_backends.py

Updated the logic for MPIBackend and get_mpi_env function to not use the obtuse 'win' string search. 
closes #875

[MRG] Fix MPIBackend platform logic

---

setup.py

Replaces distutils imports with corollary setuptools classes because distutils is deprecated and supposedly removed from python 3.12.
closes #879

build: update setup.py to remove deprecated distutils import

---

hnn_core/gui/gui.py

The plot generated when loading data had the same default scaling and smoothing that is applied to simulation data. This PR removes smoothing and scaling so the plot respects the raw loaded data. The user can then choose how to adjust the scaling and smoothing as they see fit.

[MRG] GUI Dipole load data figure scaling

---

hnn_core/gui/gui.py
hnn_core/tests/test_gui.py

Added a button to delete a single drive.
I decided to refactor previous functions that changed the GUI's state as class methods. The key challenge I faced was how to close a parent object based a nested child delete button. Keeping the external functions would have required creating additional logic and data structures to keep track of drive indices upon creation and editing.  As an added benefit I found that the refactor made the method calls more straight-forward and easier to understand. 
closes #887

[MRG] GUI: delete single drive button

---

hnn_core/gui/_viz_manager.py

Added a post-processing function to adjust figures after they have been constructed
This was created for a special case where L2 and L5 dipole plots should have the same axis limits. There wasn't a simple way to set axis limits upon plot creation so the post-process implementation seemed like the most simple solution while keeping the current APIs intact.
Admittedly this solution is a bit hacky as it renders the first set a plots and quickly re-renders the adjustment (looks like a flicker). Perhaps adding keywords to not render certain plot calls would be a solution.

[MRG] feat: post-processing function to adjust figures 

---

doc/whats_new.rst
hnn_core/gui/_viz_manager.py

Added widget for adjusting the minimum frequency of the spectrogram plots.

[MRG] GUI spectrogram min freq widget

---

doc/whats_new.rst
hnn_core/network.py
hnn_core/network_builder.py
hnn_core/tests/assets/jones2009_3x3_drives.json
hnn_core/tests/test_gui.py
hnn_core/tests/test_io.py
hnn_core/tests/test_network.py

Closes #885. This PR allows updating synaptic weights by a scalar gain parameter. Synaptic weights are grouped by E/I connections types (EE, EI, IE, II).
Updates can be performed as:
```py
net.update_weights(e_e=2.0, copy=False)
net2 = net.update_weights(e_e=2.0, copy=True
```

[MRG] Add method to modify synaptic gain

---

hnn_core/gui/_viz_manager.py

1. Removed tight_layout method in favor of the constrained layout argument
* The tight layout was displaying a warning for spectrogram plots. This change removes that message.
2. fixed set selected index for figure controls after new figure is generated
* When creating a blank figure, the GUI was not automatically opening/selecting the new figure tab. This was because the selected index was only being set for the figure tabs but not the figure control tabs. This made them not synchronous, and when the two tab groups are later linked, it reverted to the un-updated index.

[MRG] GUI fix minor glitches

---

hnn_core/network.py
hnn_core/tests/test_gui.py

The eq method was refactored to be more flexible to new methods added to the object. 
The eq method loops over class attributes and compares the values to assess equality. 
* Previously we used the dir() function to list all of the classes attributes and methods and then filtered for only the attributes.
* We used a hard-coded list of attributes and methods we wanted to pass over. This was annoying because each new method added to the Network class had to be manually added to this list. 
* This change uses the var() function to grab just the list of attributes from the class so new methods don't need to be coded manually. 
* The change was also made to the test_gui.py>check_equal_networks function, which had logic adapted from the eq method.

[MRG] Update Network eq method

---

hnn_core/gui/gui.py

Changed logic in `_update_cell_params_vbox` to properly build the `cell_parameters_key`.
The problem was here: 
https://github.com/jonescompneurolab/hnn-core/blob/7a42650dbe41e0a740612fe374e5b19e3e8e8d7c/hnn_core/gui/gui.py#L1974-L1975
`if "Biophysics"` will always evaluate to `True`.
closes #911

[MRG] fix synapses properties rendering

---

doc/whats_new.rst
hnn_core/gui/gui.py
hnn_core/viz.py

Note that this does not change the L2 names inherent in the `cell_types` which are loaded dynamically in the gui, such as shown here: https://github.com/jonescompneurolab/hnn-core/issues/904#issue-2589984642

[MRG] chore: change fixed L2 names in gui to L2/3

---

doc/whats_new.rst
hnn_core/cell_response.py
hnn_core/tests/test_cell_response.py

[MRG] ENH: add new property to access spike times by cell type

---

hnn_core/cell_response.py
hnn_core/tests/test_viz.py
hnn_core/viz.py

Adding functionality to specify spike types to invert when creating the input histogram. 
So far:
Still need to test, etc. More coming soon :)

[MRG] Flip specified drives in input histogram

---

hnn_core/gui/_viz_manager.py
hnn_core/tests/test_gui.py
hnn_core/viz.py

This fixes a prior bug with my prior addition to `_clear_axis` where it would always remove the histogram's inverted second Axes object. It now only removes if it the desired Axes being cleared is a spike histogram.

fix: clear_axis contextually removes second axis

---

hnn_core/gui/_viz_manager.py
hnn_core/gui/gui.py
hnn_core/tests/test_gui.py

[MRG] New widget to adjust default smoothing value in gui

---

doc/whats_new.rst
hnn_core/cell_response.py
hnn_core/tests/test_viz.py
hnn_core/viz.py

**Changes**
1. Changed the spike raster colors to have a white background and use the current color cycle's first 4 colors.
2. Added argument to change the cell colors by either dictionary or list of colors.
3. Added argument to add custom cell types if the Network has different cell types than the default. 
4. Changed the line lengths to 1 to prevent overlap
With new colors
With new shorter lines. 
**Question:**
* ~~Should the API allow users to be able to specify colors?~~ Yes
* With this new implementation the user could technically change the plot colors outside of the hnn-core API if they changed the Matplotlib color cycle and default background with the matplotlib API. 
closes #888

[MRG] Spikes raster plot colors

---

hnn_core/gui/gui.py

Prints log messages to the bottom of the output instead of the top.

fix: log messages to the bottom of the output window instead of the top

---

hnn_core/gui/_viz_manager.py

This fixes #937 . 
Note that, yes, the GUI console log message is sent to the beginning of the log, not the end. However, this appears to be the case for all logged GUI messages, and I will make a separate issue for fixing that.

[MRG]: fix: add GUI log error msg if spect args invalid

---

hnn_core/gui/_viz_manager.py
hnn_core/gui/gui.py
hnn_core/tests/test_gui.py

Adding sections to Simulation tab, separating our the default values for visualization parameters that will be updated on 'run' 
Improvements to network connectivity tab, adjusting spacing of Vboxes, text indentation, adding css classes to more easily target sections, updating display of the receptor names

[MRG] Add Min/Max Frequency and Add Visual Updates Ahead of 0.4

---

hnn_core/gui/gui.py

This PR adds a class that captures print statements in the logger and updates the display in the log output widget so that new items always appear at the top of the log. I made some updates to the formatting of the log messages as well to make them more readable, see img below

[MRG] Add class to capture print messages to the logger

---

examples/howto/plot_batch_simulate.py
hnn_core/batch_simulate.py
hnn_core/hnn_io.py
hnn_core/tests/test_batch_simulate.py

Adjusted parameter descriptions and added more informative explanations for waveforms and simulation outputs.

ENH: Refactor `BatchSimulate` Example and Improve Documentation

---

.github/workflows/unix_unit_tests.yml
Makefile
pyproject.toml
setup.cfg
setup.py

This is a small change for the purposes of replacing our previous linting with `flake8` to use the faster `ruff check` linting. For previous discussion on why this is a good idea, see the parts of #934 discussing `ruff` *linting* specifically (as opposed to "formatting"). This PR was forked off from that discussion. Note that this current PR is NOT about using `ruff format` to change our code-formatting-style. Instead, the "linting" in `ruff check` is limited to error detection (such as syntax errors) and some limited PEP8 formatting violation detection. Again, see the other issue for a more exhaustive discussion of these things, including the terminology around them.
Note: for anyone doing testing on an existing install, this DOES require that you will have to install the `ruff` Python …

[MRG] Replace `flake8` linting with `ruff` linting

---

hnn_core/cell_response.py
hnn_core/network.py
hnn_core/network_models.py
hnn_core/tests/test_cell_response.py
hnn_core/tests/test_network.py
hnn_core/viz.py

Work in Progress to refactor the hard-coded parts in the code for renaming cells in HNN.

WIP: refactoring hard coded parts in renaming cells in HNN

---

hnn_core/tests/test_drives.py

This is a trivial fix for stochastic, difficult-to-reproduce test failure. Rarely, and seemingly only on Python 3.8 `Unit Test` runners, this test will fail due to the random Poisson mean interval exceeding the `approx` threshold. Here is an example case: https://github.com/asoplata/hnn-core/actions/runs/12952951618/job/36131478285#step:9:164 . I noticed the same thing happening on the first time I tried to run the tests for #971 ; however, since I told it to re-run the failed jobs, now I can't find any data on the previously-failed jobs. (It's possible that when you re-run failed jobs, maybe you can't access the old failed data using GitHub Actions?). As you can see in the above example, the test failed because the mean event interval was around 18.98, which is *just* outside of the …

[MRG] fix: relax test for poisson drive stats

---

doc/conf.py

Now that #971 is merged, we need to make a very small follow-up change to fix a circular dependency, which is in this PR. Merging #971 has created a new file available at https://jonescompneurolab.github.io/hnn-core/dev/_static/versions.json . This file, which is now publicly accessible, can be used as the proper `versions.json` for all documentation site builds going forward. This updates the dev build of the documentation so that it uses this new file (which is ALSO updated itself through the dev doc build).
After this, anytime we want to rename or add an additional version (like when we make a release), we only need to edit the file referenced in config line in this PR.

[MRG] maint: update versions.json sphinx link

---

.github/workflows/unix_unit_tests.yml

Resolves #992. This is a tiny fix needed for our MacOS CI runners to start working again.
Short version: For some reason, some time during last week, `miniconda` started installing older, incompatible versions of `conda-forge`'s OpenMPI in our CI runners by default. This PR "raises the floor" of the version so that they should begin working again.
Long version: I don't know what caused this change, but I strongly suspect it is something on Anaconda's end. I did a lot of testing, and for some reason, `miniconda` defaults to installing an older (<5) version of `conda-forge`'s OpenMPI by default on `osx-arm64`. To make it more perplexing, it installed `4.1.1`, which is lower than even the `noarch` label of `4.1.3` as can be seen here https://anaconda.org/conda-forge/openmpi . I *also* …

[MRG] hotfix version install of MPI on macos CI

---

doc/whats_new.md
hnn_core/gui/_viz_manager.py
hnn_core/tests/test_gui.py
hnn_core/tests/test_viz.py
hnn_core/viz.py

Added support for reversed y-axis in `plot_tfr_morlet` to allow min_freq > max_freq
Fixes #898

[MRG] ENH: Refactor dipole visualization to invert y-axis when min_freq > max_freq

---

hnn_core/gui/gui.py
hnn_core/parallel_backends.py
hnn_core/tests/test_gui.py
hnn_core/tests/test_parallel_backends.py

The GUI MPI was not working on HPC systems where the number of cores partitioned to an instance is less than the total cores of a node. 
This fix uses the number of available cores to the process instead of the total number of cores of the system. 
**Work done**
1. Use psutil to get number of available cores instead of total system cores for Linux and Windows. Mac will still use total system cores.
2. Exposed the number of cores selection for the MPI backend. Default is set to 1 and the maximum is set to the number of available cores. 
3. Fixed the issue where the backend sub-options (n cores) was not displaying for the default (joblib) on startup  
closes #870

[MRG] Fix GUI MPI available cores

---

Makefile
doc/contributing.md
pyproject.toml
setup.py

This is a pretty trivial change: this adds support for automatic *local* install and usage of [codespell](https://github.com/codespell-project/codespell). This fixes an annoyance since, currently, we have a CI runner for `codespell` usage (see https://github.com/codespell-project/codespell ), but there's no automatic local way to test for such spelling mistakes before you push your commits.
This fixes the problem, in that now, `codespell` is used the same as our linting: it's installed as part of the `[test]` or `[dev]` options (e.g. `pip install "hnn_core[test]"`), and run during a developer's local `make test`. The TOML change also enables it to ignore any locally-built artifacts (which are not a problem for the CI runner).
After this, hopefully no more follow-up "`flake8 fix`" or …

[MRG] DEV: Add local codespell usage to dev install

---

.github/workflows/issue-metrics.yml

This copies over the exact content of the template for the `issue_metrics` workflow from
https://github.com/github/issue-metrics/blob/main/docs/example-workflows.md EXCEPT for the `SEARCH_QUERY` and removal of `assignees`. This may help with #935 , possibly due to the change in `permissions: contents`.

[MRG] fix: copy template for monthly metrics workflow

---

hnn_core/tests/test_parallel_backends.py

If you made any PRs to `hnn-core` recently, you may have noticed frequent, *but random/stochastic* failures in the unit tests. Failed workflows can be found here: https://github.com/jonescompneurolab/hnn-core/actions?query=is%3Afailure . The failures are stochastic, meaning they occur randomly and unpredictably, but usually, simply re-running any failed tests once or twice enables the unit tests to pass. In every single case I have inspected, these tests tend to fail in the MacOS MPI test cases specifically, in the function you can invoke via 
```
pytest ./hnn_core/tests/test_parallel_backends.py::TestParallelBackends::test_run_mpibackend_hwthreading
```
These failures always occur with an error like the following: `RuntimeError: MPI simulation failed. Return code: 143` where the return …

[WIP] Fix: Potentially fix new MPI test failures

---

README.md
doc/install.md

Trivial PR: add a warning about not using Python 3.13 with `hnn-core`. Related to #947 .

doc: add warning about py3.13

---

README.md

After the new standalone installation page was merged into the documentation, I forgot to update the link from the README, since this step had to be done AFTER the PR was fully merged (cyclic dependency). Since I recently deleted the old branch it was sitting on, the current Install link now gives a 404.
I am going to merge this immediately, of my own accord, because it fixes a broken link on our current README.

[MRG] hotfix: update link to current install webpage

---

doc/whats_new.md

This significantly adds to the `doc/whats_new.md` page with mention of both PRs and contributors that were not added at the time their work was merged. There were many missing contributions that should now be present in our changelog. I believe I've added all outstanding PRs that were merged into `master` (as opposed to the HDF5 changes in `upstream`'s `network-rw` branch, etc.).
I also re-organized them into a couple of categories (API, GUI, Bug, other).
Since this is only additions to contribution-documentation, this should be an easy merge.
Note that this is NOT the final version of the release notes for v0.4. I will write up some actual summary content similar to https://numpy.org/doc/stable/release/2.2.0-notes.html when we get closer to the v0.4 release very soon.

[MRG]: DOC Update whatsnew

---

.github/workflows/linkcheck.yml
doc/api.rst
examples/howto/plot_batch_simulate.py
hnn_core/__init__.py
hnn_core/batch_simulate.py

This PR does the following:
1. Promotes `BatchSimulate` to a top-level class befitting its status as a member of the public API. This means that its import is analogous to other public classes: just like `from hnn_core import Network`, you can now `from hnn_core import BatchSimulate` without having to import it strictly from its own module. This puts it on equal footing with the other classes described in the public API https://jonescompneurolab.github.io/hnn-core/stable/api.html . The example script for `BatchSimulate` has been updated to include this new import way.
2. Moves around the docstrings of `BatchSimulate` so they display properly on the sphinx build (i.e. the code website).
3. Adds a WARNING to the docstring of any `backend` options which indicate that only `loky` should be …

[MRG]: Update and include `BatchSimulate` documentation

---

hnn_core/gui/_viz_manager.py

Resolves #1023 , fixing the PSD layer GUI plots' x-axes.

[MRG] fix: expand custom x-axis to psd layer plots

---

README.md
doc/_static/versions.json
hnn_core/__init__.py

Note: This does not include the usual change to `doc/conf.py` because the existing file previously (incorrectly) had the version set to `0.4` (when it should have been `0.4rc4`).
Also note that Linkcheck will fail due to a new documention website page reference in the README. This is expected and will be fixed when the `gh-pages` branch is updated momentarily.

MAINT: 0.4 Release

---

doc/api.rst
doc/whats_new.md
examples/howto/plot_batch_simulate.py
hnn_core/__init__.py
setup.py

This is an emergency patch due to several issues that our tests did not catch. This will become the new v0.4 release commit.
This commit does two things:
1. Reverts `BatchSimulate` from a top-level import to how it was imported previously, which now requires manual import, as shown in its example. I've added relevant instructions in the example that indicates it requires some extra dependencies to function.
2. Adds a line in `setup.py` which is required for `setup.py` use (but not `pyproject.toml`) that indicates to the relevant Python Packaging repository that the README is in markdown format. I've also be re-writing the "How to make a release" guide a bunch, including reversing the order of instructings for `twine` uploading vs testing the distributable.
It turns out that the reason …

maint: patch: v0.4

---

Makefile
hnn_core/__init__.py

This second emergency fix today fixes a very sneaky bug introduced in the *packaged* but not source versions of HNN-core for MacOS and Linux installs on x86_64 processors (not arm64 or Windows). In the name of sanity, I am going to switch the version to v0.4.1 thereby introducing semantic versioning, in order to provide a newer but still close version to Pypi.
Previously, there was a small inconsistency unnoticed by me, and introduced by our support for arm64. The existing release instructions https://github.com/jonescompneurolab/hnn-core/wiki/How-to-make-a-release tell you that, before uploading the distributable package, you should
```
rm -rf hnn-core/hnn_core/mod/x86_64
```
Since similar functionality is in our root Makefile, but the latter includes code for handling our new …

patch: v0.4.1 architecture fix

---

doc/conf.py
doc/whats_new.md
hnn_core/__init__.py

This increases the master version from `v0.4.1` (the most recent stable) to `v0.5.0.dev0`. The addition of the "micro" version specificer (see https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers and
https://packaging.python.org/en/latest/discussions/versioning/ ) does not appear to cause any problems with the documentation generation as far as I've been able to test, and enables us to describe/version/publish bugfix patches in the more common manner.
This also re-locates all the version-programming code in `doc/conf.py` to the same section. Previously this code was distributed across the file, but there were also inconsistencies between the string-detection of development versions for the HTML version switcher versus Binder. These inconsistencies …

maint: bump versions to 0.5.0.dev0 after v0.4.1 stable

---

doc/install.md

This adds a section to the beginning of the Install page with information on how to use HNN through both NSG and Google CoLab. This is related to our grant milestones of improving ease of use for NSG.
I have explicitly added the version note about HNN v0.3 on NSG, but I am in contact with NSG about them updating the version. Hopefully we should be able to remove that note soon.

[MRG] doc: add cloud install instructions

---

doc/install.md

As per discussion with @dylansdaniels  recently, this reverses the addition of content to the Install page that describes how to run HNN in the cloud without a local install.
However, instead of removing it entirely, this still leaves in a link to the Cloud guidance on the current Textbook website. I think this is the best solution for two reasons:
1. Any user who is going to the Code-website's install page may be interested in test-driving HNN in the cloud before they install it, and it is good that they are made aware that *that is possible*. Frequently, for software packages, some users (such as myself) tend to learn about a software package, then immediately look up the Github repo before reviewing the non-code website for a package. In this case, all users reviewing any installation …

[MRG] Replace "HNN-cloud usage" instructions with link

---

doc/conf.py
doc/install.md

This is a major revamp of our Installation page. As per #950, this adds a new section at the top of the install page for recommending and describing how a user should install HNN-Core using our newly-published `conda` packages.
Observers will note that the conda package install path allows for MPI etc. usage, but is **significantly** easier of an install. I (and a few others) have tested the `conda` install method on all listed platforms, including MPI support on a Windows WSL install.
Because we still want to retain `pip` install path instructions and descriptions, I have left them in the Install page but tried to shorten them where I can. In particular:
- The description of and usage guide for both Joblib and MPI have been moved to our new Textbook site, using the [new tutorial here for …

[MRG] DOC: Add `conda` install instructions

---

.github/workflows/linkcheck.yml
README.md

This pull request updates the Linkcheck workflow to modify its frequency and reduce unnecessary runs.
1. The workflow now:
- Runs only on every push/merge to the `master` branch.
- Executes on a scheduled basis on the 1st and 15th of each month at midnight UTC.
- No longer runs on every pull request (including subsequent updates).
Closes #1031

[ENH]: Update Linkcheck Schedule to Reduce Frequency

---

README.md

This changes the hosting location of the
HNN Icon displayed, since we recently
updated the homepage domain.

[MRG] Fix HNN logo hosting locn

---

.github/workflows/windows_unit_tests.yml
hnn_core/mod/vecevent.mod
pyproject.toml
setup.py

This may resolve #1052, but needs to be comprehensively tested.
In testing for #1052, the issue seemed to be that, with NEURON 8.2.7 on Windows, `nrnivmodl` is no longer able to compile our `vecevent.mod` file, and complains about inconsistent types. Here is example output:
```
(test-nrn-827) C:\Users\austi\mod-test>nrnivmodl
x86_64-w64-mingw32-gcc.exe -DDLL_EXPORT -DPIC -I/cygdrive/c/nrn/bin//../include -I/cygdrive/c/nrn/bin//../src/scopmath -I/cygdrive/c/nrn/bin//../src/nrnoc -I/cygdrive/c/nrn/bin//../src/oc  -c mod_func.c
nocmodl vecevent
Translating vecevent.mod into vecevent.c
Notice: VERBATIM blocks are not thread safe
x86_64-w64-mingw32-gcc.exe -DDLL_EXPORT -DPIC -I/cygdrive/c/nrn/bin//../include -I/cygdrive/c/nrn/bin//../src/scopmath -I/cygdrive/c/nrn/bin//../src/nrnoc …
```

[MRG] Bugfix: Update vecevent mod

---

Makefile
dev_scripts/regenerate_base_network.py
doc/contributing.md
hnn_core/tests/regenerate_test_network.py

This adds a new script, `dev_scripts/regenerate_base_network.py`, for doing what its name implies, and adds accompanying documentation in the Contributing Guide. This also makes some small improvements to the Contributing Guide in general.
As far as I could tell, this fixes an undocumented "missing documentation" issue: it was not explicitly clear how the default network file for the GUI (`hnn_core/param/jones2009_base.json`) was created, nor how it should be re-created in the future if changes were needed. Doing some historical research, it appears that the current `jones2009_base.json` file at the time it was last updated (commit af4b10588e5af12a48c1ffff809395f4d8376307 ) was created by using the "flat JSON" `hnn_core/param/default.json` as the input to the function …

[MRG] Add explicit base net regen

---

.github/workflows/publish-packages-on-tag.yml

This fixes what I believe is a new issue introduced through #1073. In the original PR, in the `on: push:` block, I included mention of the `master` branch and the glob for the `tags` we wanted, believing that they functioned in a Boolean AND sense. I.e., I assumed that I thought that both values had to be satisfied before the workflow would run. This appears to be incorrect: between `tags` and `branches` appears to function like a Boolean OR, meaning the publishing workflow is currently running on every push to `master`, OR every pushed tag matching the glob.
Instead, we only want the latter, i.e. the tag-specific case. This fixes the issue by removing any branch-based rules for the publishing workflow, instead making it entirely rely on version tags being pushed. Since we tend to push …

[MRG] Fix package publishing to only use tags

---

hnn_core/parallel_backends.py

This is potentially and quick-and-easy bandaid for making MPI Timeout happen a *little* less frequently (see #774). I have intentionally not touched the timeout used in `run_subprocess` via `timeout_cycles` because I haven't had time to investigate its consequences. However, raising the other timeouts *may* make MPI Timeouts less likely to happen, *especially* in our Unit test runs (where they happen a significant fraction of the time, like more 10% of the time, IMHO).
@ntolley @dylansdaniels Is there any reason to think that increasing the length of these timeouts would DAMAGE simulation quality or reliability in any way? I still need to investigate that myself.

[WIP] parallel: double non-encoding timeout lengths

---

doc/Makefile
doc/conf.py

For some reason, recent linkchecks with this DOI have been failing, even though (I'm not 100% sure) it was working fine before. This change simply adds this particular publication DOI link to both linkcheck ignore lists.
Example failing can be found here: https://github.com/jonescompneurolab/hnn-core/actions/runs/17408169238/job/49423224430#step:5:486

[MRG] fix: add a DOI to linkcheck ignore

---

pyproject.toml

This is a very tiny config change: this tells codespell to ignore all directories and files matching the glob `*venv*`. This way, any local virtual environment that includes the string "venv" such as at `my-venv` or `.venv` will be ignored from codespell, which usually finds errors in the files of the venvs.
This is useful in part because, *soon*, we will be able to have full-feature HNN installs possible through venvs alone, without `conda`...

[MRG] tiny: ignore all "venv" for codespell
